// Generated by dart2js, the Dart to JavaScript compiler.
(function($){
var supportsDirectProtoAccess=function(){var z=function(){}
z.prototype={p:{}}
var y=new z()
return y.__proto__&&y.__proto__.p===z.prototype.p}()
function map(a){a=Object.create(null)
a.x=0
delete a.x
return a}var A=map()
var B=map()
var C=map()
var D=map()
var E=map()
var F=map()
var G=map()
var H=map()
var J=map()
var K=map()
var L=map()
var M=map()
var N=map()
var O=map()
var P=map()
var Q=map()
var R=map()
var S=map()
var T=map()
var U=map()
var V=map()
var W=map()
var X=map()
var Y=map()
var Z=map()
function I(){}
init()
$=I.p
$.Cq=function(){}
function setupProgram(a){"use strict"
function generateAccessor(a8,a9,b0){var g=a8.split("-")
var f=g[0]
var e=f.length
var d=f.charCodeAt(e-1)
var c
if(g.length>1)c=true
else c=false
d=d>=60&&d<=64?d-59:d>=123&&d<=126?d-117:d>=37&&d<=43?d-27:0
if(d){var b=d&3
var a0=d>>2
var a1=f=f.substring(0,e-1)
var a2=f.indexOf(":")
if(a2>0){a1=f.substring(0,a2)
f=f.substring(a2+1)}if(b){var a3=b&2?"r":""
var a4=b&1?"this":"r"
var a5="return "+a4+"."+f
var a6=b0+".prototype.g"+a1+"="
var a7="function("+a3+"){"+a5+"}"
if(c)a9.push(a6+"$reflectable("+a7+");\n")
else a9.push(a6+a7+";\n")}if(a0){var a3=a0&2?"r,v":"v"
var a4=a0&1?"this":"r"
var a5=a4+"."+f+"=v"
var a6=b0+".prototype.s"+a1+"="
var a7="function("+a3+"){"+a5+"}"
if(c)a9.push(a6+"$reflectable("+a7+");\n")
else a9.push(a6+a7+";\n")}}return f}function defineClass(a0,a1){var g=[]
var f="function "+a0+"("
var e=""
for(var d=0;d<a1.length;d++){if(d!=0)f+=", "
var c=generateAccessor(a1[d],g,a0)
var b="p_"+c
f+=b
e+="this."+c+" = "+b+";\n"}if(supportsDirectProtoAccess)e+="this."+"$deferredAction"+"();"
f+=") {\n"+e+"}\n"
f+=a0+".builtin$cls=\""+a0+"\";\n"
f+="$desc=$collectedClasses."+a0+"[1];\n"
f+=a0+".prototype = $desc;\n"
if(typeof defineClass.name!="string")f+=a0+".name=\""+a0+"\";\n"
f+=g.join("")
return f}var z=supportsDirectProtoAccess?function(b,c){var g=b.prototype
g.__proto__=c.prototype
g.constructor=b
g["$is"+b.name]=b
return convertToFastObject(g)}:function(){function tmp(){}return function(b,a0){tmp.prototype=a0.prototype
var g=new tmp()
convertToSlowObject(g)
var f=b.prototype
var e=Object.keys(f)
for(var d=0;d<e.length;d++){var c=e[d]
g[c]=f[c]}g["$is"+b.name]=b
g.constructor=b
b.prototype=g
return g}}()
function finishClasses(a3){var g=init.allClasses
a3.combinedConstructorFunction+="return [\n"+a3.constructorsList.join(",\n  ")+"\n]"
var f=new Function("$collectedClasses",a3.combinedConstructorFunction)(a3.collected)
a3.combinedConstructorFunction=null
for(var e=0;e<f.length;e++){var d=f[e]
var c=d.name
var b=a3.collected[c]
var a0=b[0]
b=b[1]
g[c]=d
a0[c]=d}f=null
var a1=init.finishedClasses
function finishClass(c0){if(a1[c0])return
a1[c0]=true
var a4=a3.pending[c0]
if(a4&&a4.indexOf("+")>0){var a5=a4.split("+")
a4=a5[0]
var a6=a5[1]
finishClass(a6)
var a7=g[a6]
var a8=a7.prototype
var a9=g[c0].prototype
var b0=Object.keys(a8)
for(var b1=0;b1<b0.length;b1++){var b2=b0[b1]
if(!u.call(a9,b2))a9[b2]=a8[b2]}}if(!a4||typeof a4!="string"){var b3=g[c0]
var b4=b3.prototype
b4.constructor=b3
b4.$isa=b3
b4.$deferredAction=function(){}
return}finishClass(a4)
var b5=g[a4]
if(!b5)b5=existingIsolateProperties[a4]
var b3=g[c0]
var b4=z(b3,b5)
if(a8)b4.$deferredAction=mixinDeferredActionHelper(a8,b4)
if(Object.prototype.hasOwnProperty.call(b4,"%")){var b6=b4["%"].split(";")
if(b6[0]){var b7=b6[0].split("|")
for(var b1=0;b1<b7.length;b1++){init.interceptorsByTag[b7[b1]]=b3
init.leafTags[b7[b1]]=true}}if(b6[1]){b7=b6[1].split("|")
if(b6[2]){var b8=b6[2].split("|")
for(var b1=0;b1<b8.length;b1++){var b9=g[b8[b1]]
b9.$nativeSuperclassTag=b7[0]}}for(b1=0;b1<b7.length;b1++){init.interceptorsByTag[b7[b1]]=b3
init.leafTags[b7[b1]]=false}}b4.$deferredAction()}if(b4.$isGv)b4.$deferredAction()}var a2=Object.keys(a3.pending)
for(var e=0;e<a2.length;e++)finishClass(a2[e])}function finishAddStubsHelper(){var g=this
while(!g.hasOwnProperty("$deferredAction"))g=g.__proto__
delete g.$deferredAction
var f=Object.keys(g)
for(var e=0;e<f.length;e++){var d=f[e]
var c=d.charCodeAt(0)
var b
if(d!=="^"&&d!=="$reflectable"&&c!==43&&c!==42&&(b=g[d])!=null&&b.constructor===Array&&d!=="<>")addStubs(g,b,d,false,[])}convertToFastObject(g)
g=g.__proto__
g.$deferredAction()}function mixinDeferredActionHelper(b,c){var g
if(c.hasOwnProperty("$deferredAction"))g=c.$deferredAction
return function foo(){var f=this
while(!f.hasOwnProperty("$deferredAction"))f=f.__proto__
if(g)f.$deferredAction=g
else{delete f.$deferredAction
convertToFastObject(f)}b.$deferredAction()
f.$deferredAction()}}function processClassData(b0,b1,b2){b1=convertToSlowObject(b1)
var g
var f=Object.keys(b1)
var e=false
var d=supportsDirectProtoAccess&&b0!="a"
for(var c=0;c<f.length;c++){var b=f[c]
var a0=b.charCodeAt(0)
if(b==="static"){processStatics(init.statics[b0]=b1.static,b2)
delete b1.static}else if(a0===43){w[g]=b.substring(1)
var a1=b1[b]
if(a1>0)b1[g].$reflectable=a1}else if(a0===42){b1[g].$defaultValues=b1[b]
var a2=b1.$methodsWithOptionalArguments
if(!a2)b1.$methodsWithOptionalArguments=a2={}
a2[b]=g}else{var a3=b1[b]
if(b!=="^"&&a3!=null&&a3.constructor===Array&&b!=="<>")if(d)e=true
else addStubs(b1,a3,b,false,[])
else g=b}}if(e)b1.$deferredAction=finishAddStubsHelper
var a4=b1["^"],a5,a6,a7=a4
var a8=a7.split(";")
a7=a8[1]==""?[]:a8[1].split(",")
a6=a8[0]
a5=a6.split(":")
if(a5.length==2){a6=a5[0]
var a9=a5[1]
if(a9)b1.$signature=function(b3){return function(){return init.types[b3]}}(a9)}if(a6)b2.pending[b0]=a6
b2.combinedConstructorFunction+=defineClass(b0,a7)
b2.constructorsList.push(b0)
b2.collected[b0]=[m,b1]
i.push(b0)}function processStatics(a2,a3){var g=Object.keys(a2)
for(var f=0;f<g.length;f++){var e=g[f]
if(e==="^")continue
var d=a2[e]
var c=e.charCodeAt(0)
var b
if(c===43){v[b]=e.substring(1)
var a0=a2[e]
if(a0>0)a2[b].$reflectable=a0
if(d&&d.length)init.typeInformation[b]=d}else if(c===42){m[b].$defaultValues=d
var a1=a2.$methodsWithOptionalArguments
if(!a1)a2.$methodsWithOptionalArguments=a1={}
a1[e]=b}else if(typeof d==="function"){m[b=e]=d
h.push(e)
init.globalFunctions[e]=d}else if(d.constructor===Array)addStubs(m,d,e,true,h)
else{b=e
processClassData(e,d,a3)}}}function addStubs(b1,b2,b3,b4,b5){var g=0,f=b2[g],e
if(typeof f=="string")e=b2[++g]
else{e=f
f=b3}var d=[b1[b3]=b1[f]=e]
e.$stubName=b3
b5.push(b3)
for(;g<b2.length;g+=2){e=b2[g+1]
if(typeof e!="function")break
e.$stubName=b2[g+2]
d.push(e)
if(e.$stubName){b1[e.$stubName]=e
b5.push(e.$stubName)}}g++
for(var c=0;c<d.length;g++,c++)d[c].$callName=b2[g]
var b=b2[g]
b2=b2.slice(++g)
var a0=b2[0]
var a1=a0>>1
var a2=(a0&1)===1
var a3=a0===3
var a4=a0===1
var a5=b2[1]
var a6=a5>>1
var a7=(a5&1)===1
var a8=a1+a6!=d[0].length
var a9=b2[2]
var b0=2*a6+a1+3
if(b){e=tearOff(d,b2,b4,b3,a8)
b1[b3].$getter=e
e.$getterStub=true
if(b4){init.globalFunctions[b3]=e
b5.push(b)}b1[b]=e
d.push(e)
e.$stubName=b
e.$callName=null}}function tearOffGetter(b,c,d,e){return e?new Function("funcs","reflectionInfo","name","H","c","return function tearOff_"+d+y+++"(x) {"+"if (c === null) c = H.qm("+"this, funcs, reflectionInfo, false, [x], name);"+"return new c(this, funcs[0], x, name);"+"}")(b,c,d,H,null):new Function("funcs","reflectionInfo","name","H","c","return function tearOff_"+d+y+++"() {"+"if (c === null) c = H.qm("+"this, funcs, reflectionInfo, false, [], name);"+"return new c(this, funcs[0], null, name);"+"}")(b,c,d,H,null)}function tearOff(b,c,d,e,f){var g
return d?function(){if(g===void 0)g=H.qm(this,b,c,true,[],e).prototype
return g}:tearOffGetter(b,c,e,f)}var y=0
if(!init.libraries)init.libraries=[]
if(!init.mangledNames)init.mangledNames=map()
if(!init.mangledGlobalNames)init.mangledGlobalNames=map()
if(!init.statics)init.statics=map()
if(!init.typeInformation)init.typeInformation=map()
if(!init.globalFunctions)init.globalFunctions=map()
var x=init.libraries
var w=init.mangledNames
var v=init.mangledGlobalNames
var u=Object.prototype.hasOwnProperty
var t=a.length
var s=map()
s.collected=map()
s.pending=map()
s.constructorsList=[]
s.combinedConstructorFunction="function $reflectable(fn){fn.$reflectable=1;return fn};\n"+"var $desc;\n"
for(var r=0;r<t;r++){var q=a[r]
var p=q[0]
var o=q[1]
var n=q[2]
var m=q[3]
var l=q[4]
var k=!!q[5]
var j=l&&l["^"]
if(j instanceof Array)j=j[0]
var i=[]
var h=[]
processStatics(l,s)
x.push([p,o,i,h,n,j,k,m])}finishClasses(s)}var dart = [["","",,H,{
"^":"",
FK:{
"^":"a;Q"}}],["","",,J,{
"^":"",
t:function(a){return void 0},
Qu:function(a,b,c,d){return{i:a,p:b,e:c,x:d}},
ks:function(a){var z,y,x,w
z=a[init.dispatchPropertyName]
if(z==null)if($.Bv==null){H.XD()
z=a[init.dispatchPropertyName]}if(z!=null){y=z.p
if(!1===y)return z.i
if(!0===y)return a
x=Object.getPrototypeOf(a)
if(y===x)return z.i
if(z.e===x)throw H.b(P.SY("Return interceptor for "+H.d(y(a,z))))}w=H.w3(a)
if(w==null){y=Object.getPrototypeOf(a)
if(y==null||y===Object.prototype)return C.ZQ
else return C.vB}return w},
Gv:{
"^":"a;",
m:function(a,b){return a===b},
giO:function(a){return H.wP(a)},
X:["VE",function(a){return H.a5(a)}],
"%":"ApplicationCacheErrorEvent|AutocompleteErrorEvent|ClipboardEvent|DOMError|ErrorEvent|Event|FileError|InputEvent|MediaError|MediaKeyError|Navigator|NavigatorUserMediaError|PositionError|SQLError|SVGAnimatedEnumeration|SVGAnimatedLength|SVGAnimatedLengthList|SVGAnimatedNumber|SpeechRecognitionError"},
yE:{
"^":"Gv;",
X:function(a){return String(a)},
giO:function(a){return a?519018:218159},
$isa2:1},
PE:{
"^":"Gv;",
m:function(a,b){return null==b},
X:function(a){return"null"},
giO:function(a){return 0}},
Ue:{
"^":"Gv;",
giO:function(a){return 0}},
iC:{
"^":"Ue;"},
kd:{
"^":"Ue;",
X:function(a){return String(a)}},
G:{
"^":"Gv;",
uy:function(a,b){if(!!a.immutable$list)throw H.b(P.f(b))},
PP:function(a,b){if(!!a.fixed$length)throw H.b(P.f(b))},
h:function(a,b){if(!!a.fixed$length)H.R(P.f("add"))
a.push(b)},
Ay:function(a,b){var z
for(z=J.Nx(b);z.D();)this.h(a,z.gk())},
aN:function(a,b){var z,y
z=a.length
for(y=0;y<z;++y){b.$1(a[y])
if(a.length!==z)throw H.b(P.a4(a))}},
es:function(a,b,c){var z,y,x
z=a.length
for(y=b,x=0;x<z;++x){y=c.$2(y,a[x])
if(a.length!==z)throw H.b(P.a4(a))}return y},
Zv:function(a,b){return a[b]},
gFV:function(a){if(a.length>0)return a[0]
throw H.b(H.Wp())},
grZ:function(a){var z=a.length
if(z>0)return a[z-1]
throw H.b(H.Wp())},
gor:function(a){return a.length!==0},
X:function(a){return P.WE(a,"[","]")},
gu:function(a){return new J.m1(a,a.length,0,null)},
giO:function(a){return H.wP(a)},
gv:function(a){return a.length},
sv:function(a,b){if(b<0)throw H.b(P.D(b,null,null))
this.PP(a,"set length")
a.length=b},
p:function(a,b){if(typeof b!=="number"||Math.floor(b)!==b)throw H.b(P.p(b))
if(b>=a.length||b<0)throw H.b(P.D(b,null,null))
return a[b]},
q:function(a,b,c){this.uy(a,"indexed set")
if(b>=a.length||!1)throw H.b(P.D(b,null,null))
a[b]=c},
$iszM:1,
$aszM:null,
$iscX:1,
$ascX:null},
m1:{
"^":"a;Q,a,b,c",
gk:function(){return this.c},
D:function(){var z,y,x
z=this.Q
y=z.length
if(this.a!==y)throw H.b(P.a4(z))
x=this.b
if(x>=y){this.c=null
return!1}this.c=z[x]
this.b=x+1
return!0}},
F:{
"^":"Gv;",
gzP:function(a){return a===0?1/a<0:a<0},
zQ:function(a){if(a>0){if(a!==1/0)return Math.round(a)}else if(a>-1/0)return 0-Math.round(0-a)
throw H.b(P.f(""+a))},
X:function(a){if(a===0&&1/a<0)return"-0.0"
else return""+a},
giO:function(a){return a&0x1FFFFFFF},
R:function(a,b){return a*b},
V:function(a,b){var z=a%b
if(z===0)return 0
if(z>0)return z
if(b<0)return z-b
else return z+b},
wG:function(a,b){var z
if(a>0)z=b>31?0:a>>>b
else{z=b>31?31:b
z=a>>z>>>0}return z},
w:function(a,b){if(typeof b!=="number")throw H.b(P.p(b))
return a<b},
$islf:1},
im:{
"^":"F;",
$isCP:1,
$islf:1,
$isP:1},
VA:{
"^":"F;",
$isCP:1,
$islf:1},
E:{
"^":"Gv;",
O2:function(a,b){if(b<0)throw H.b(P.D(b,null,null))
if(b>=a.length)throw H.b(P.D(b,null,null))
return a.charCodeAt(b)},
g:function(a,b){if(typeof b!=="string")throw H.b(P.p(b))
return a+b},
Nj:function(a,b,c){if(c==null)c=a.length
if(typeof c!=="number"||Math.floor(c)!==c)H.R(P.p(c))
if(b<0)throw H.b(P.D(b,null,null))
if(b>c)throw H.b(P.D(b,null,null))
if(c>a.length)throw H.b(P.D(c,null,null))
return a.substring(b,c)},
yn:function(a,b){return this.Nj(a,b,null)},
bS:function(a){var z,y,x,w,v
z=a.trim()
y=z.length
if(y===0)return z
if(this.O2(z,0)===133){x=J.mm(z,1)
if(x===y)return""}else x=0
w=y-1
v=this.O2(z,w)===133?J.r9(z,w):y
if(x===0&&v===y)return z
return z.substring(x,v)},
R:function(a,b){var z,y
if(0>=b)return""
if(b===1||a.length===0)return a
if(b!==b>>>0)throw H.b(C.Eq)
for(z=a,y="";!0;){if((b&1)===1)y=z+y
b=b>>>1
if(b===0)break
z+=z}return y},
XU:function(a,b,c){if(c>a.length)throw H.b(P.TE(c,0,a.length,null,null))
return a.indexOf(b,c)},
OY:function(a,b){return this.XU(a,b,0)},
Is:function(a,b,c){if(c>a.length)throw H.b(P.TE(c,0,a.length,null,null))
return H.m2(a,b,c)},
gl0:function(a){return a.length===0},
X:function(a){return a},
giO:function(a){var z,y,x
for(z=a.length,y=0,x=0;x<z;++x){y=536870911&y+a.charCodeAt(x)
y=536870911&y+((524287&y)<<10>>>0)
y^=y>>6}y=536870911&y+((67108863&y)<<3>>>0)
y^=y>>11
return 536870911&y+((16383&y)<<15>>>0)},
p:function(a,b){if(b>=a.length||!1)throw H.b(P.D(b,null,null))
return a[b]},
$isI:1,
static:{Ga:function(a){if(a<256)switch(a){case 9:case 10:case 11:case 12:case 13:case 32:case 133:case 160:return!0
default:return!1}switch(a){case 5760:case 6158:case 8192:case 8193:case 8194:case 8195:case 8196:case 8197:case 8198:case 8199:case 8200:case 8201:case 8202:case 8232:case 8233:case 8239:case 8287:case 12288:case 65279:return!0
default:return!1}},mm:function(a,b){var z,y
for(z=a.length;b<z;){y=C.xB.O2(a,b)
if(y!==32&&y!==13&&!J.Ga(y))break;++b}return b},r9:function(a,b){var z,y
for(;b>0;b=z){z=b-1
y=C.xB.O2(a,z)
if(y!==32&&y!==13&&!J.Ga(y))break}return b}}}}],["","",,H,{
"^":"",
wV:function(a,b){var z
if(b!=null){z=b.x
if(z!=null)return z}return!!J.t(a).$isXj},
d:function(a){var z
if(typeof a==="string")return a
if(typeof a==="number"){if(a!==0)return""+a}else if(!0===a)return"true"
else if(!1===a)return"false"
else if(a==null)return"null"
z=J.Lz(a)
if(typeof z!=="string")throw H.b(P.p(a))
return z},
wP:function(a){var z=a.$identityHash
if(z==null){z=Math.random()*0x3fffffff|0
a.$identityHash=z}return z},
lh:function(a){var z,y
z=C.w2(J.t(a))
if(z==="Object"){y=String(a.constructor).match(/^\s*function\s*(\S*)\s*\(/)[1]
if(typeof y==="string")z=/^\w+$/.test(y)?y:z}if(z.length>1&&C.xB.O2(z,0)===36)z=C.xB.yn(z,1)
return(z+H.ia(H.oX(a),0,null)).replace(/[^<,> ]+/g,function(b){return init.mangledGlobalNames[b]||b})},
a5:function(a){return"Instance of '"+H.lh(a)+"'"},
of:function(a,b){if(a==null||typeof a==="boolean"||typeof a==="number"||typeof a==="string")throw H.b(P.p(a))
return a[b]},
aw:function(a,b,c){if(a==null||typeof a==="boolean"||typeof a==="number"||typeof a==="string")throw H.b(P.p(a))
a[b]=c},
Yx:function(a){return a},
b:function(a){var z
if(a==null)a=new P.LK()
z=new Error()
z.dartException=a
if("defineProperty" in Object){Object.defineProperty(z,"message",{get:H.Ju})
z.name=""}else z.toString=H.Ju
return z},
Ju:function(){return J.Lz(this.dartException)},
R:function(a){throw H.b(a)},
Ru:function(a){var z,y,x,w,v,u,t,s,r,q,p,o,n,m
z=new H.Am(a)
if(a==null)return
if(typeof a!=="object")return a
if("dartException" in a)return z.$1(a.dartException)
else if(!("message" in a))return a
y=a.message
if("number" in a&&typeof a.number=="number"){x=a.number
w=x&65535
if((C.jn.wG(x,16)&8191)===10)switch(w){case 438:return z.$1(H.T3(H.d(y)+" (Error "+w+")",null))
case 445:case 5007:v=H.d(y)+" (Error "+w+")"
return z.$1(new H.W0(v,null))}}if(a instanceof TypeError){v=$.WD()
u=$.OI()
t=$.PH()
s=$.D1()
r=$.rx()
q=$.Kr()
p=$.zO()
$.Bi()
o=$.eA()
n=$.ko()
m=v.qS(y)
if(m!=null)return z.$1(H.T3(y,m))
else{m=u.qS(y)
if(m!=null){m.method="call"
return z.$1(H.T3(y,m))}else{m=t.qS(y)
if(m==null){m=s.qS(y)
if(m==null){m=r.qS(y)
if(m==null){m=q.qS(y)
if(m==null){m=p.qS(y)
if(m==null){m=s.qS(y)
if(m==null){m=o.qS(y)
if(m==null){m=n.qS(y)
v=m!=null}else v=!0}else v=!0}else v=!0}else v=!0}else v=!0}else v=!0}else v=!0
if(v)return z.$1(new H.W0(y,m==null?null:m.method))}}return z.$1(new H.vV(typeof y==="string"?y:""))}if(a instanceof RangeError){if(typeof y==="string"&&y.indexOf("call stack")!==-1)return new P.VS()
return z.$1(new P.AT(!1,null,null,null))}if(typeof InternalError=="function"&&a instanceof InternalError)if(typeof y==="string"&&y==="too much recursion")return new P.VS()
return a},
CU:function(a){if(a==null||typeof a!='object')return J.v1(a)
else return H.wP(a)},
ft:function(a,b,c,d,e,f,g){if(c===0)return new H.dr(a).$0()
else if(c===1)return new H.TL(a,d).$0()
else if(c===2)return new H.KX(a,d,e).$0()
else if(c===3)return new H.uZ(a,d,e,f).$0()
else if(c===4)return new H.OQ(a,d,e,f,g).$0()
else throw H.b(new P.HG("Unsupported number of arguments for wrapped closure"))},
kg:function(a,b){var z
if(a==null)return
z=a.$identity
if(!!z)return z
z=function(c,d,e,f){return function(g,h,i,j){return f(c,e,d,g,h,i,j)}}(a,b,$,H.ft)
a.$identity=z
return z},
iA:function(a,b,c,d,e,f){var z,y,x,w,v,u,t,s,r,q,p,o,n,m
z=b[0]
z.$stubName
y=z.$callName
if(!!J.t(c).$iszM){z.$reflectionInfo=c
x=H.zh(z).f}else x=c
w=d?Object.create(new H.Bp().constructor.prototype):Object.create(new H.q(null,null,null,null).constructor.prototype)
w.$initialize=w.constructor
if(d)v=function(){this.$initialize()}
else{u=$.yj
$.yj=u+1
u=new Function("a","b","c","d","this.$initialize(a,b,c,d);"+u)
v=u}w.constructor=v
v.prototype=w
u=!d
if(u){t=e.length==1&&!0
s=H.bx(a,z,t)
s.$reflectionInfo=c}else{w.$name=f
s=z
t=!1}if(typeof x=="number")r=function(g){return function(){return init.types[g]}}(x)
else if(u&&typeof x=="function"){q=t?H.yS:H.DV
r=function(g,h){return function(){return g.apply({$receiver:h(this)},arguments)}}(x,q)}else throw H.b("Error in reflectionInfo.")
w.$signature=r
w[y]=s
for(u=b.length,p=1;p<u;++p){o=b[p]
n=o.$callName
if(n!=null){m=d?o:H.bx(a,o,t)
w[n]=m}}w["call*"]=s
w.$requiredArgCount=z.$requiredArgCount
w.$defaultValues=z.$defaultValues
return v},
vq:function(a,b,c,d){var z=H.DV
switch(b?-1:a){case 0:return function(e,f){return function(){return f(this)[e]()}}(c,z)
case 1:return function(e,f){return function(g){return f(this)[e](g)}}(c,z)
case 2:return function(e,f){return function(g,h){return f(this)[e](g,h)}}(c,z)
case 3:return function(e,f){return function(g,h,i){return f(this)[e](g,h,i)}}(c,z)
case 4:return function(e,f){return function(g,h,i,j){return f(this)[e](g,h,i,j)}}(c,z)
case 5:return function(e,f){return function(g,h,i,j,k){return f(this)[e](g,h,i,j,k)}}(c,z)
default:return function(e,f){return function(){return e.apply(f(this),arguments)}}(d,z)}},
bx:function(a,b,c){var z,y,x,w,v,u
if(c)return H.Hf(a,b)
z=b.$stubName
y=b.length
x=a[z]
w=b==null?x==null:b===x
v=!w||y>=27
if(v)return H.vq(y,!w,z,b)
if(y===0){w=$.mJ
if(w==null){w=H.Iq("self")
$.mJ=w}w="return function(){return this."+H.d(w)+"."+H.d(z)+"();"
v=$.yj
$.yj=v+1
return new Function(w+H.d(v)+"}")()}u="abcdefghijklmnopqrstuvwxyz".split("").splice(0,y).join(",")
w="return function("+u+"){return this."
v=$.mJ
if(v==null){v=H.Iq("self")
$.mJ=v}v=w+H.d(v)+"."+H.d(z)+"("+u+");"
w=$.yj
$.yj=w+1
return new Function(v+H.d(w)+"}")()},
Z4:function(a,b,c,d){var z,y
z=H.DV
y=H.yS
switch(b?-1:a){case 0:throw H.b(H.Ef("Intercepted function with no arguments."))
case 1:return function(e,f,g){return function(){return f(this)[e](g(this))}}(c,z,y)
case 2:return function(e,f,g){return function(h){return f(this)[e](g(this),h)}}(c,z,y)
case 3:return function(e,f,g){return function(h,i){return f(this)[e](g(this),h,i)}}(c,z,y)
case 4:return function(e,f,g){return function(h,i,j){return f(this)[e](g(this),h,i,j)}}(c,z,y)
case 5:return function(e,f,g){return function(h,i,j,k){return f(this)[e](g(this),h,i,j,k)}}(c,z,y)
case 6:return function(e,f,g){return function(h,i,j,k,l){return f(this)[e](g(this),h,i,j,k,l)}}(c,z,y)
default:return function(e,f,g,h){return function(){h=[g(this)]
Array.prototype.push.apply(h,arguments)
return e.apply(f(this),h)}}(d,z,y)}},
Hf:function(a,b){var z,y,x,w,v,u,t,s
z=H.oN()
y=$.P4
if(y==null){y=H.Iq("receiver")
$.P4=y}x=b.$stubName
w=b.length
v=a[x]
u=b==null?v==null:b===v
t=!u||w>=28
if(t)return H.Z4(w,!u,x,b)
if(w===1){y="return function(){return this."+H.d(z)+"."+H.d(x)+"(this."+H.d(y)+");"
u=$.yj
$.yj=u+1
return new Function(y+H.d(u)+"}")()}s="abcdefghijklmnopqrstuvwxyz".split("").splice(0,w-1).join(",")
y="return function("+s+"){return this."+H.d(z)+"."+H.d(x)+"(this."+H.d(y)+", "+s+");"
u=$.yj
$.yj=u+1
return new Function(y+H.d(u)+"}")()},
qm:function(a,b,c,d,e,f){var z
b.fixed$length=Array
if(!!J.t(c).$iszM){c.fixed$length=Array
z=c}else z=c
return H.iA(a,b,z,!!d,e,f)},
aH:function(a){if(typeof a==="string"||a==null)return a
throw H.b(H.aq(H.lh(a),"String"))},
eQ:function(a){throw H.b(new P.t7("Cyclic initialization for static "+H.d(a)))},
J:function(a,b){if(a!=null)a.$builtinTypeInfo=b
return a},
oX:function(a){if(a==null)return
return a.$builtinTypeInfo},
IM:function(a,b){return H.Y9(a["$as"+H.d(b)],H.oX(a))},
W8:function(a,b,c){var z=H.IM(a,b)
return z==null?null:z[c]},
Kp:function(a,b){var z=H.oX(a)
return z==null?null:z[b]},
Ko:function(a,b){if(a==null)return"dynamic"
else if(typeof a==="object"&&a!==null&&a.constructor===Array)return a[0].builtin$cls+H.ia(a,1,b)
else if(typeof a=="function")return a.builtin$cls
else if(typeof a==="number"&&Math.floor(a)===a)return C.jn.X(a)
else return},
ia:function(a,b,c){var z,y,x,w,v,u
if(a==null)return""
z=new P.Rn("")
for(y=b,x=!0,w=!0,v="";y<a.length;++y){if(x)x=!1
else z.Q=v+", "
u=a[y]
if(u!=null)w=!1
v=z.Q+=H.d(H.Ko(u,c))}return w?"":"<"+H.d(z)+">"},
Y9:function(a,b){if(typeof a=="function"){a=H.ml(a,null,b)
if(a==null||typeof a==="object"&&a!==null&&a.constructor===Array)b=a
else if(typeof a=="function")b=H.ml(a,null,b)}return b},
ml:function(a,b,c){return a.apply(b,c)},
F3:function(a){var z=$.NF
return"Instance of "+(z==null?"<Unknown>":z.$1(a))},
kE:function(a){return H.wP(a)},
iw:function(a,b,c){Object.defineProperty(a,b,{value:c,enumerable:false,writable:true,configurable:true})},
w3:function(a){var z,y,x,w,v,u
z=$.NF.$1(a)
y=$.nw[z]
if(y!=null){Object.defineProperty(a,init.dispatchPropertyName,{value:y,enumerable:false,writable:true,configurable:true})
return y.i}x=$.vv[z]
if(x!=null)return x
w=init.interceptorsByTag[z]
if(w==null){z=$.TX.$2(a,z)
if(z!=null){y=$.nw[z]
if(y!=null){Object.defineProperty(a,init.dispatchPropertyName,{value:y,enumerable:false,writable:true,configurable:true})
return y.i}x=$.vv[z]
if(x!=null)return x
w=init.interceptorsByTag[z]}}if(w==null)return
x=w.prototype
v=z[0]
if(v==="!"){y=H.Va(x)
$.nw[z]=y
Object.defineProperty(a,init.dispatchPropertyName,{value:y,enumerable:false,writable:true,configurable:true})
return y.i}if(v==="~"){$.vv[z]=x
return x}if(v==="-"){u=H.Va(x)
Object.defineProperty(Object.getPrototypeOf(a),init.dispatchPropertyName,{value:u,enumerable:false,writable:true,configurable:true})
return u.i}if(v==="+")return H.Lc(a,x)
if(v==="*")throw H.b(P.SY(z))
if(init.leafTags[z]===true){u=H.Va(x)
Object.defineProperty(Object.getPrototypeOf(a),init.dispatchPropertyName,{value:u,enumerable:false,writable:true,configurable:true})
return u.i}else return H.Lc(a,x)},
Lc:function(a,b){var z=Object.getPrototypeOf(a)
Object.defineProperty(z,init.dispatchPropertyName,{value:J.Qu(b,z,null,null),enumerable:false,writable:true,configurable:true})
return b},
Va:function(a){return J.Qu(a,!1,null,!!a.$isXj)},
VF:function(a,b,c){var z=b.prototype
if(init.leafTags[a]===true)return J.Qu(z,!1,null,!!z.$isXj)
else return J.Qu(z,c,null,null)},
XD:function(){if(!0===$.Bv)return
$.Bv=!0
H.Z1()},
Z1:function(){var z,y,x,w,v,u,t,s
$.nw=Object.create(null)
$.vv=Object.create(null)
H.kO()
z=init.interceptorsByTag
y=Object.getOwnPropertyNames(z)
if(typeof window!="undefined"){window
x=function(){}
for(w=0;w<y.length;++w){v=y[w]
u=$.x7.$1(v)
if(u!=null){t=H.VF(v,z[v],u)
if(t!=null){Object.defineProperty(u,init.dispatchPropertyName,{value:t,enumerable:false,writable:true,configurable:true})
x.prototype=u}}}}for(w=0;w<y.length;++w){v=y[w]
if(/^[A-Za-z_]/.test(v)){s=z[v]
z["!"+v]=s
z["~"+v]=s
z["-"+v]=s
z["+"+v]=s
z["*"+v]=s}}},
kO:function(){var z,y,x,w,v,u,t
z=C.M1()
z=H.ud(C.Mc,H.ud(C.hQ,H.ud(C.XQ,H.ud(C.XQ,H.ud(C.Jh,H.ud(C.lR,H.ud(C.ur(C.w2),z)))))))
if(typeof dartNativeDispatchHooksTransformer!="undefined"){y=dartNativeDispatchHooksTransformer
if(typeof y=="function")y=[y]
if(y.constructor==Array)for(x=0;x<y.length;++x){w=y[x]
if(typeof w=="function")z=w(z)||z}}v=z.getTag
u=z.getUnknownTag
t=z.prototypeForTag
$.NF=new H.dC(v)
$.TX=new H.wN(u)
$.x7=new H.VX(t)},
ud:function(a,b){return a(b)||b},
m2:function(a,b,c){return a.indexOf(b,c)>=0},
ys:{
"^":"a;",
X:function(a){return P.vW(this)}},
LP:{
"^":"ys;Q,a,b",
x4:function(a){if(typeof a!=="string")return!1
if("__proto__"===a)return!1
return this.a.hasOwnProperty(a)},
p:function(a,b){if(!this.x4(b))return
return this.qP(b)},
qP:function(a){return this.a[a]},
aN:function(a,b){var z,y,x
z=this.b
for(y=0;y<z.length;++y){x=z[y]
b.$2(x,this.qP(x))}}},
FD:{
"^":"a;Q,a,b,c,d,e,f,r",
static:{zh:function(a){var z,y,x
z=a.$reflectionInfo
if(z==null)return
z.fixed$length=Array
z=z
y=z[0]
x=z[1]
return new H.FD(a,z,(y&1)===1,y>>1,x>>1,(x&1)===1,z[2],null)}}},
Zr:{
"^":"a;Q,a,b,c,d,e",
qS:function(a){var z,y,x
z=new RegExp(this.Q).exec(a)
if(z==null)return
y=Object.create(null)
x=this.a
if(x!==-1)y.arguments=z[x+1]
x=this.b
if(x!==-1)y.argumentsExpr=z[x+1]
x=this.c
if(x!==-1)y.expr=z[x+1]
x=this.d
if(x!==-1)y.method=z[x+1]
x=this.e
if(x!==-1)y.receiver=z[x+1]
return y},
static:{cM:function(a){var z,y,x,w,v,u
a=a.replace(String({}),'$receiver$').replace(new RegExp("[[\\]{}()*+?.\\\\^$|]",'g'),'\\$&')
z=a.match(/\\\$[a-zA-Z]+\\\$/g)
if(z==null)z=[]
y=z.indexOf("\\$arguments\\$")
x=z.indexOf("\\$argumentsExpr\\$")
w=z.indexOf("\\$expr\\$")
v=z.indexOf("\\$method\\$")
u=z.indexOf("\\$receiver\\$")
return new H.Zr(a.replace('\\$arguments\\$','((?:x|[^x])*)').replace('\\$argumentsExpr\\$','((?:x|[^x])*)').replace('\\$expr\\$','((?:x|[^x])*)').replace('\\$method\\$','((?:x|[^x])*)').replace('\\$receiver\\$','((?:x|[^x])*)'),y,x,w,v,u)},S7:function(a){return function($expr$){var $argumentsExpr$='$arguments$'
try{$expr$.$method$($argumentsExpr$)}catch(z){return z.message}}(a)},Mj:function(a){return function($expr$){try{$expr$.$method$}catch(z){return z.message}}(a)}}},
W0:{
"^":"Ge;Q,a",
X:function(a){var z=this.a
if(z==null)return"NullError: "+H.d(this.Q)
return"NullError: Cannot call \""+H.d(z)+"\" on null"}},
L4:{
"^":"Ge;Q,a,b",
X:function(a){var z,y
z=this.a
if(z==null)return"NoSuchMethodError: "+H.d(this.Q)
y=this.b
if(y==null)return"NoSuchMethodError: Cannot call \""+H.d(z)+"\" ("+H.d(this.Q)+")"
return"NoSuchMethodError: Cannot call \""+H.d(z)+"\" on \""+H.d(y)+"\" ("+H.d(this.Q)+")"},
static:{T3:function(a,b){var z,y
z=b==null
y=z?null:b.method
return new H.L4(a,y,z?null:b.receiver)}}},
vV:{
"^":"Ge;Q",
X:function(a){var z=this.Q
return C.xB.gl0(z)?"Error":"Error: "+z}},
Am:{
"^":"r;Q",
$1:function(a){if(!!J.t(a).$isGe)if(a.$thrownJsError==null)a.$thrownJsError=this.Q
return a}},
dr:{
"^":"r;Q",
$0:function(){return this.Q.$0()}},
TL:{
"^":"r;Q,a",
$0:function(){return this.Q.$1(this.a)}},
KX:{
"^":"r;Q,a,b",
$0:function(){return this.Q.$2(this.a,this.b)}},
uZ:{
"^":"r;Q,a,b,c",
$0:function(){return this.Q.$3(this.a,this.b,this.c)}},
OQ:{
"^":"r;Q,a,b,c,d",
$0:function(){return this.Q.$4(this.a,this.b,this.c,this.d)}},
r:{
"^":"a;",
X:function(a){return"Closure"},
gKu:function(){return this},
gKu:function(){return this}},
Bp:{
"^":"r;"},
q:{
"^":"Bp;Q,a,b,c",
m:function(a,b){if(b==null)return!1
if(this===b)return!0
if(!(b instanceof H.q))return!1
return this.Q===b.Q&&this.a===b.a&&this.b===b.b},
giO:function(a){var z,y
z=this.b
if(z==null)y=H.wP(this.Q)
else y=typeof z!=="object"?J.v1(z):H.wP(z)
return(y^H.wP(this.a))>>>0},
static:{DV:function(a){return a.Q},yS:function(a){return a.b},oN:function(){var z=$.mJ
if(z==null){z=H.Iq("self")
$.mJ=z}return z},Iq:function(a){var z,y,x,w,v
z=new H.q("self","target","receiver","name")
y=Object.getOwnPropertyNames(z)
y.fixed$length=Array
x=y
for(y=x.length,w=0;w<y;++w){v=x[w]
if(z[v]===a)return v}}}},
Pe:{
"^":"Ge;Q",
X:function(a){return this.Q},
static:{aq:function(a,b){return new H.Pe("CastError: Casting value of type "+a+" to incompatible type "+H.d(b))}}},
tc:{
"^":"Ge;Q",
X:function(a){return"RuntimeError: "+H.d(this.Q)},
static:{Ef:function(a){return new H.tc(a)}}},
N5:{
"^":"a;Q,a,b,c,d,e,f",
x4:function(a){var z,y
if(typeof a==="string"&&a!=="__proto__"){z=this.a
if(z==null)return!1
return z[a]!=null}else if(typeof a==="number"&&(a&0x3ffffff)===a){y=this.b
if(y==null)return!1
return y[a]!=null}else return this.CX(a)},
CX:function(a){var z=this.c
if(z==null)return!1
return this.Fh(z[this.xi(a)],a)>=0},
p:function(a,b){var z,y,x
if(typeof b==="string"&&b!=="__proto__"){z=this.a
if(z==null)return
y=z[b]
return y==null?null:y.a}else if(typeof b==="number"&&(b&0x3ffffff)===b){x=this.b
if(x==null)return
y=x[b]
return y==null?null:y.a}else return this.aa(b)},
aa:function(a){var z,y,x
z=this.c
if(z==null)return
y=z[this.xi(a)]
x=this.Fh(y,a)
if(x<0)return
return y[x].a},
q:function(a,b,c){var z,y
if(typeof b==="string"&&b!=="__proto__"){z=this.a
if(z==null){z=H.QE()
this.a=z}this.ti(z,b,c)}else if(typeof b==="number"&&(b&0x3ffffff)===b){y=this.b
if(y==null){y=H.QE()
this.b=y}this.ti(y,b,c)}else this.xw(b,c)},
xw:function(a,b){var z,y,x,w
z=this.c
if(z==null){z=H.QE()
this.c=z}y=this.xi(a)
x=z[y]
if(x==null)z[y]=[this.y4(a,b)]
else{w=this.Fh(x,a)
if(w>=0)x[w].a=b
else x.push(this.y4(a,b))}},
aN:function(a,b){var z,y
z=this.d
y=this.f
for(;z!=null;){b.$2(z.Q,z.a)
if(y!==this.f)throw H.b(P.a4(this))
z=z.b}},
ti:function(a,b,c){var z=a[b]
if(z==null)a[b]=this.y4(b,c)
else z.a=c},
y4:function(a,b){var z,y
z=new H.vh(a,b,null,null)
if(this.d==null){this.e=z
this.d=z}else{y=this.e
z.c=y
y.b=z
this.e=z}++this.Q
this.f=this.f+1&67108863
return z},
xi:function(a){return J.v1(a)&0x3ffffff},
Fh:function(a,b){var z,y
if(a==null)return-1
z=a.length
for(y=0;y<z;++y)if(J.mG(a[y].Q,b))return y
return-1},
X:function(a){return P.vW(this)},
static:{QE:function(){var z=Object.create(null)
z["<non-identifier-key>"]=z
delete z["<non-identifier-key>"]
return z}}},
vh:{
"^":"a;Q,a,b,c"},
dC:{
"^":"r;Q",
$1:function(a){return this.Q(a)}},
wN:{
"^":"r;Q",
$2:function(a,b){return this.Q(a,b)}},
VX:{
"^":"r;Q",
$1:function(a){return this.Q(a)}},
VR:{
"^":"a;Q,a,b,c",
X:function(a){return"RegExp/"+this.Q+"/"},
static:{v4:function(a,b,c,d){var z,y,x,w
H.Yx(a)
z=b?"m":""
y=c?"":"i"
x=d?"g":""
w=function(){try{return new RegExp(a,z+y+x)}catch(v){return v}}()
if(w instanceof RegExp)return w
throw H.b(new P.aE("Illegal RegExp pattern ("+String(w)+")",a,null))}}}}],["","",,X,{
"^":"",
Dk:{
"^":"a;"},
O:{
"^":"Dk;a,Q",
wZ:function(a,b){if((b&$.ot)!==0||(b&$.ha)!==0)return a[0]
if((b&$.dv)!==0||(b&$.o6)!==0)return a[2]
return a[1]}}}],["","",,D,{
"^":"",
U:{
"^":"a;Q,a,b,c,d,e,f,r,x,y",
hV:function(a){return this.e.$1(a)},
static:{V:function(a,b){a.e=new D.a6(b)
a.hV(a)}}},
a6:{
"^":"r;Q",
$1:function(a){a.b=this.Q
a.c=0
a.d=null}}}],["","",,Z,{
"^":"",
JN:function(a,b){var z,y,x,w
z=C.xB.OY(a,":")
if(z===-1&&b!=null)return b.ownerDocument.createElementNS(b.namespaceURI,a)
if(z>=0){y=C.xB.Nj(a,0,z)
x=C.xB.yn(a,z+1)}else{y=a
x=null}if(C.tQ.x4(y))w=C.tQ.p(0,y)
else{x=a
w=null}return w==null?b.ownerDocument.createElementNS(b.namespaceURI,a):b.ownerDocument.createElementNS(w,x)},
PY:{
"^":"a;x:Q>,y:a>,N:b>,fg:c>",
m:function(a,b){var z,y
if(b==null)return!1
z=J.t(b)
if(!!z.$isPY){y=this.gN(this)===z.gN(b)&&this.gfg(this)===z.gfg(b)
if(y)z=this.gx(this)===z.gx(b)&&this.gy(this)===z.gy(b)
else z=!1}else z=!1
return z},
X:function(a){return H.d(this.gx(this))+", "+H.d(this.gy(this))+", "+H.d(this.gN(this))+", "+H.d(this.gfg(this))}},
d7:{
"^":"PY;x:d*,y:e*,N:f>,fg:r>,Q,a,b,c"}}],["","",,K,{
"^":"",
Q:function(){var z,y,x
z=new D.U(P.L(null,null,null,null,P.P),[],[],0,null,null,null,null,null,null)
D.V(z,C.VK)
y=document.querySelector(".demos-container")
x=new S.nB(new P.N(null),new P.N(null),null,null)
if(y==null)H.R(P.p("Root element for SelectionScope cannot be null"))
x.b=y
z=new K.Vi([["aaa",3,25],["bbb",2,10],["ccc",-1,145],["ddd",2,125],["eee",3,30],["fff",4,10],["ggg",3,30],["hhh",2,10],["iii",3,20],["jjj",3,13],["kkk",3,7],["lll",4,15],["mmm",4,5],["nnn",0,13],["ooo",0,12]],400,300,new X.O(z,null),S.T([y],x))
z.$2(".squarify",0)
z.$2(".slice",1)
z.$2(".dice",2)
z.$2(".slicedice",3)},
Vi:{
"^":"r;Q,a,b,c,d",
$2:function(a,b){var z,y,x,w,v,u,t
z=new Q.S(!1,[1,1],0,0.5*(1+Math.sqrt(5)),new Q.W(),Q.oQ(),Q.M(),Q.Z())
z.e=b
y=this.a
x=this.b
z.d=[y,x]
w=z.mq(this.Q,1,0,2)
v=w[0]
u=J.Y(v)
u.sx(v,0)
u.sy(v,0)
u.sZ(v,C.Nm.gFV(z.d))
u=C.Nm.grZ(z.d)
v.x=u
z.pc([v],v.r*u/v.c)
z.hN(v)
t=S.iz(null,null,a,this.d).Y(0,"div")
t.bv(0,"position","relative")
t.bv(0,"width",""+y+"px")
t.bv(0,"height",""+x+"px")
x=S.E2(null,null,".node",t).uD(S.T9(w),null).b.Y(0,"div")
x.vB("left",new K.VY())
x.vB("top",new K.RH())
x.vB("width",new K.Jn())
x.vB("height",new K.tL())
x.vB("background",new K.NO(this.c))
x.yy(new K.uG())
x.DJ("node",S.T9(!0))}},
VY:{
"^":"r;",
$3:function(a,b,c){return H.d(J.Rd(a))+"px"}},
RH:{
"^":"r;",
$3:function(a,b,c){return H.d(J.C0(a))+"px"}},
Jn:{
"^":"r;",
$3:function(a,b,c){return H.d(P.u(0,J.zd(a)-1))+"px"}},
tL:{
"^":"r;",
$3:function(a,b,c){return H.d(P.u(0,J.tw(a)-1))+"px"}},
NO:{
"^":"r;Q",
$3:function(a,b,c){var z,y,x,w,v,u
z=J.Y(a)
if(J.pO(z.gwd(a))){y=this.Q
z=z.gph(a)
x=y.a
w=x.Q
if(!w.x4(z)){v=x.a
w.q(0,z,v.length)
v.push(z)}v=x.b
u=v.length!==0?v[C.CD.V(w.p(0,z),x.b.length)]:0
z=!!J.t(u).$iscX?y.wZ(u,1):u}else z=null
return z}},
uG:{
"^":"r;",
$3:function(a,b,c){var z=J.Y(a)
return J.pO(z.gwd(a))?null:z.gph(a)}}},1],["","",,Q,{
"^":"",
t6:[function(a){return a.gwd(a)},"$1","M",2,0,1],
lo:[function(a){return a.gM(a)},"$1","Z",2,0,2],
JD:[function(a,b){return b.gM(b).T(0,a.gM(a))},"$2","oQ",4,0,3],
eC:{
"^":"a;",
eI:["mq",function(a,b,c,d){var z,y,x,w,v,u,t,s,r,q,p,o
z=[]
for(y=new J.m1(a,15,0,null);y.D();){x=y.c
w=J.U6(x)
z.push(this.q7(w.p(x,c),w.p(x,d),0))}for(v=0;v<15;++v){u=a[v][b]
if(u===-1)continue
t=z[v]
s=z[u]
y=s.a
if(y.length===0)s.a=[t]
else y.push(t)
t.Q=s
t.d=s.d+1
for(y=t.a,y=new J.m1(y,y.length,0,null);y.D();){r=y.c
r.d=r.gyt()+1}}q=[]
p=[H.J(new H.U5(z,new Q.ny()),[H.Kp(z,0)]).Zv(0,0)]
for(;p.length>0;){o=p.pop()
C.Nm.Ay(p,J.OG(o))
q.push(o)}return q}]},
ny:{
"^":"r;",
$1:function(a){return a.gyt()===0}},
xT:{
"^":"a;eT:Q>,wd:a>,ph:b>,M:c>,yt:d<"},
S:{
"^":"eC;c,d,e,f,r,Q,a,b",
sOb:function(a){this.c=a},
q7:function(a,b,c){var z=new Q.Gn(0,0,0,0,0,!1,null,[],"",null,0)
z.b=a
z.c=b
z.d=c
return z},
h5:function(a,b,c,d,e,f){var z,y,x,w,v,u,t,s,r,q
z=d.d
y=d.e
x=c>0?C.ON.zQ(f/c):0
w=d.f
if(c===w){if(e||x>d.r)x=d.r
for(v=new J.m1(b,b.length,0,null),u=x>0;v.D();){t=v.c
s=J.Y(t)
s.sx(t,z)
s.sy(t,y)
s.sqV(t,x)
s=d.d
r=d.f
q=u?C.ON.zQ(t.y/x):0
q=P.C(s+r-z,q)
t.r=q
z+=q}C.Nm.grZ(b).sOb(!0)
v=C.Nm.grZ(b)
u=J.Y(v)
u.sZ(v,u.gZ(v)+(d.d+d.f-z))
d.e+=x
d.r-=x}else{if(e||x>w)x=w
for(v=new J.m1(b,b.length,0,null),u=x>0;v.D();){t=v.c
s=J.Y(t)
s.sx(t,z)
s.sy(t,y)
s.sZ(t,x)
s=d.e
r=d.r
q=u?C.ON.zQ(t.y/x):0
q=P.C(s+r-y,q)
t.x=q
y+=q}C.Nm.grZ(b).sOb(!1)
v=C.Nm.grZ(b)
u=J.Y(v)
u.sqV(v,u.gqV(v)+(d.e+d.r-y))
d.d+=x
d.f-=x}},
pc:function(a,b){var z,y,x,w,v
for(z=new J.m1(a,a.length,0,null),y=b<0;z.D();){x=z.c
w=J.SW(x)
v=J.lX(w,y?0:b)
x.sY7(v<=0?0:v)}},
YF:function(a,b,c){var z,y,x,w
for(z=new J.m1(a,a.length,0,null),y=0,x=1/0;z.D();){w=z.c.gY7()
if(w<=0)continue
if(w<x)x=w
if(w>y)y=w}c*=c
b*=b
if(c>0){z=this.f
z=P.u(b*y*z/c,c/(b*x*z))}else z=1/0
return z},
hN:[function(a){var z,y,x,w,v,u,t,s,r,q,p,o,n,m,l,k
z=a.a
if(z.length!==0){y=this.Fu(a)
x=J.U6(y)
w=a.e+x.p(y,3)
v=a.f+x.gFV(y)
u=a.r-x.p(y,1)-x.p(y,3)
t=a.x-x.gFV(y)-x.p(y,2)
if(u<0){w+=u/2
u=0}if(t<0){v+=t/2
t=0}s=new Z.d7(w,v,u,t,0,0,0,0)
r=[]
q=P.z(z,!0,null)
y=this.e
if(y===1)p=u
else if(y===2)p=t
else{if(y===3)y=(a.d&1)===1?t:u
else y=P.C(u,t)
p=y}this.pc(q,u*t/a.c)
for(o=0,n=1/0;m=q.length,m>0;){l=q[m-1]
r.push(l)
o+=l.gY7()
k=this.YF(r,p,o)
if(this.e!==0||k<=n){q.pop()
n=k}else{this.h5(0,r,p,s,!1,o-r.pop().gY7())
p=P.C(s.f,s.r)
C.Nm.sv(r,0)
o=0
n=1/0}}if(r.length!==0){this.h5(0,r,p,s,!0,o)
C.Nm.sv(r,0)}C.Nm.aN(z,this.grS())}},"$1","grS",2,0,0],
Fu:function(a){return this.r.$1(a)}},
W:{
"^":"r;",
$1:function(a){return C.nx}},
Gn:{
"^":"xT;x:e*,y:f*,Z:r*,qV:x*,Y7:y@,Ob:z?,Q,a,b,c,d"}}],["","",,S,{
"^":"",
T9:function(a){return new S.QV(a)},
QV:{
"^":"r;Q",
$3:function(a,b,c){return this.Q}},
KE:{
"^":"a;"},
nB:{
"^":"a;Q,a,b,c",
Y:function(a,b){var z=Z.JN(b,this.b)
J.OG(this.b).h(0,z)
return S.T([z],this)}},
SM:{
"^":"a;Q,a",
d4:function(a,b){this.en(new S.l7(this,a,b))},
en:function(a){var z,y,x,w,v,u,t,s,r
for(z=this.Q.length,y=0;y<z;++y){x=this.Q[y]
for(w=J.Y(x),v=J.wS(w.gP9(x)),u=0;u<v;++u){t=J.i4(w.gP9(x),u)
if(t!=null){s=this.a
s=s.Q
r=H.of(t,"expando$values")
s=r==null?null:H.of(r,s.Ux())
a.$3(s,u,t)}}}},
gFV:function(a){var z,y,x,w
for(z=0;y=this.Q,z<y.length;++z){x=y[z]
for(w=0;w<J.wS(x.gP9(x));++w)if(J.i4(x.gP9(x),w)!=null)return J.i4(x.gP9(x),w)}return},
DJ:function(a,b){this.d4(b,new S.L0(a))},
vt:function(a,b,c,d){this.mF(b,S.T9(H.aH(c)),d)},
bv:function(a,b,c){return this.vt(a,b,c,null)},
mF:function(a,b,c){this.d4(b,new S.cA(a,c))},
vB:function(a,b){return this.mF(a,b,null)},
yy:function(a){this.d4(a,new S.tR())},
Y:function(a,b){return this.pH(new S.nn(b))},
pH:function(a){return S.iz(new S.p2(a),null,null,this)},
uD:function(a,b){var z,y,x,w,v,u,t,s,r,q
z=[]
y=[]
x=[]
w=new S.wK(this,b,z,y,x,new S.pE(this))
for(v=0;u=this.Q,v<u.length;++v){t=u[v]
u=this.a
s=J.Y(t)
r=s.geT(t)
u.toString
if(r==null)u=null
else{u=u.Q
q=H.of(r,"expando$values")
u=q==null?null:H.of(q,u.Ux())}w.$2(t,a.$3(u,v,s.geT(t)))}w=this.a
u=new S.R5(null,null,y,w)
s=new S.XO(u,null,z)
s.a=w
u.b=s
u.c=new S.pW(u,x,w)
return u},
Mg:function(a,b){var z=H.J([],[S.KE])
z.push(new S.zm(a,null))
this.Q=z},
Np:function(a,b,c,d){if(b!=null)d.Q=new S.Gy(this,b)
if(c!=null){this.a=c.a
this.Q=P.dH(c.Q.length,new S.XM(d,this,c),!0,S.KE)}else this.Q=P.dH(1,new S.Df(d),!1,S.KE)},
oL:function(a,b,c,d){var z,y,x,w,v,u,t,s
a=new S.NJ(this,c)
z=H.J([],[S.KE])
if(d!=null){this.a=d.a
for(y=0;x=d.Q,y<x.length;++y){w=x[y]
for(x=J.Y(w),v=0;v<J.wS(x.gP9(w));++v){u=J.i4(x.gP9(w),v)
if(u!=null){t=this.a
t=t.Q
s=H.of(u,"expando$values")
t=s==null?null:H.of(s,t.Ux())
z.push(new S.zm(a.$3(t,y,u),u))}}}}else z.push(new S.zm(a.$3(null,0,null),this.a.b))
this.Q=z},
static:{E2:function(a,b,c,d){var z=new S.SM(null,b)
z.oL(a,b,c,d)
return z},iz:function(a,b,c,d){var z,y
z={}
z.Q=a
y=new S.SM(null,b)
y.Np(b,c,d,z)
return y},T:function(a,b){var z=new S.SM(null,b)
z.Mg(a,b)
return z}}},
NJ:{
"^":"r;Q,a",
$3:function(a,b,c){var z=this.a
return c==null?new W.wz(this.Q.a.b.querySelectorAll(z)):J.MK(c,z)}},
Gy:{
"^":"r;Q,a",
$3:function(a,b,c){var z=this.a
return c==null?this.Q.a.b.querySelector(z):J.c1(c,z)}},
XM:{
"^":"r;Q,a,b",
$1:function(a){var z=this.b.Q[a]
return new S.zm(P.dH(J.wS(z.gP9(z)),new S.K5(this.Q,this.a,z),!0,null),z.geT(z))}},
K5:{
"^":"r;Q,a,b",
$1:function(a){var z,y,x,w,v
z=this.b
y=J.i4(z.gP9(z),a)
if(y!=null){z=this.a
x=z.a
w=x.Q.p(0,y)
v=this.Q.Q.$3(w,a,y)
if(w!=null){z=z.a
z.Q.q(0,v,w)}return v}else return}},
Df:{
"^":"r;Q",
$1:function(a){return new S.zm(P.dH(1,new S.WF(this.Q),!1,null),null)}},
WF:{
"^":"r;Q",
$1:function(a){return this.Q.Q.$3(null,0,null)}},
l7:{
"^":"r;Q,a,b",
$3:function(a,b,c){var z,y
z=this.a
if(z==null)z=null
else{y=this.Q.a
y.toString
z=z.$3(c==null?null:y.Q.p(0,c),b,c)}return this.b.$2(c,z)}},
L0:{
"^":"r;Q",
$2:function(a,b){var z,y
z=J.Y(a)
y=this.Q
return J.mG(b,!1)?z.gDD(a).Rz(0,y):z.gDD(a).h(0,y)}},
cA:{
"^":"r;Q,a",
$2:function(a,b){var z,y
z=b==null||C.xB.gl0(b)
y=this.Q
if(z)z=a.style.removeProperty(y)
else{z=a.style
y=C.rd.Dg(z,(z&&C.rd).Qe(z,y),b,this.a)
z=y}return z}},
tR:{
"^":"r;",
$2:function(a,b){var z=b==null?"":b
J.t3(a,z)
return z}},
nn:{
"^":"r;Q",
$3:function(a,b,c){return Z.JN(this.Q,c)}},
p2:{
"^":"r;Q",
$3:function(a,b,c){var z=this.Q.$3(a,b,c)
return z==null?null:J.RG(c,z)}},
pE:{
"^":"r;Q",
$1:function(a){var z,y
z=new P.a()
y=this.Q.a
y.toString
if(a!=null)y.Q.q(0,z,a)
return z}},
wK:{
"^":"r;Q,a,b,c,d,e",
$2:function(a,b){var z,y,x,w,v,u,t,s,r,q,p,o,n
z=J.U6(b)
y=z.gv(b)
x=J.wS(a.gP9(a))
w=Array(y)
v=Array(y)
u=Array(x)
t=P.C(x,y)
for(s=this.e,r=this.Q,q=0;q<t;++q){p=J.i4(a.gP9(a),q)
if(p!=null){o=r.a
n=z.Zv(b,q)
o.toString
if(n!=null)o.Q.q(0,p,n)
w[q]=p}else v[q]=s.$1(z.Zv(b,q))}for(;q<y;++q)v[q]=s.$1(z.Zv(b,q))
for(;q<x;++q)u[q]=J.i4(a.gP9(a),q)
this.b.push(new S.zm(v,a.geT(a)))
this.c.push(new S.zm(w,a.geT(a)))
this.d.push(new S.zm(u,a.geT(a)))}},
R5:{
"^":"SM;b,c,Q,a"},
XO:{
"^":"a;Q,a,b",
Y:function(a,b){return this.pH(new S.xL(b))},
pH:function(a){return this.QI(new S.K8(a))},
QI:function(a){var z,y,x,w,v,u,t,s,r,q,p,o,n,m,l,k,j
z=[]
for(y=this.b.length,x=this.Q,w=0;w<y;++w){v=this.b[w]
u=x.Q[w]
t=[]
for(s=v.Q,r=J.U6(s),q=r.gv(s),p=J.Y(u),o=0;o<q;++o){n=r.Zv(s,o)
if(n!=null){m=this.a
m=m.Q
l=H.of(n,"expando$values")
k=l==null?null:H.of(l,m.Ux())
j=a.$3(k,o,v.a)
m=this.a
m.toString
if(k!=null)m.Q.q(0,j,k)
J.C7(p.gP9(u),o,j)
t.push(j)}else t.push(null)}z.push(new S.zm(t,v.a))}return new S.SM(z,this.a)}},
xL:{
"^":"r;Q",
$3:function(a,b,c){return Z.JN(this.Q,c)}},
K8:{
"^":"r;Q",
$3:function(a,b,c){var z=this.Q.$3(a,b,c)
c.appendChild(z)
return z}},
pW:{
"^":"SM;b,Q,a"},
zm:{
"^":"a;P9:Q>,eT:a>"}}],["","",,H,{
"^":"",
Wp:function(){return new P.lj("No element")},
Fv:function(a){return a.gOB()},
aL:{
"^":"mW;",
gu:function(a){return new H.a7(this,this.gv(this),0,null)},
aN:function(a,b){var z,y
z=this.gv(this)
for(y=0;y<z;++y){b.$1(this.Zv(0,y))
if(z!==this.gv(this))throw H.b(P.a4(this))}},
gFV:function(a){if(this.gv(this)===0)throw H.b(H.Wp())
return this.Zv(0,0)},
tt:function(a,b){var z,y
if(b){z=H.J([],[H.W8(this,"aL",0)])
C.Nm.sv(z,this.gv(this))}else z=H.J(Array(this.gv(this)),[H.W8(this,"aL",0)])
for(y=0;y<this.gv(this);++y)z[y]=this.Zv(0,y)
return z},
br:function(a){return this.tt(a,!0)}},
a7:{
"^":"a;Q,a,b,c",
gk:function(){return this.c},
D:function(){var z,y,x,w
z=this.Q
y=J.U6(z)
x=y.gv(z)
if(this.a!==x)throw H.b(P.a4(z))
w=this.b
if(w>=x){this.c=null
return!1}this.c=y.Zv(z,w);++this.b
return!0}},
A8:{
"^":"aL;Q,a",
gv:function(a){return J.wS(this.Q)},
Zv:function(a,b){return this.Mi(J.i4(this.Q,b))},
Mi:function(a){return this.a.$1(a)},
$asaL:function(a,b){return[b]},
$asmW:function(a,b){return[b]},
$ascX:function(a,b){return[b]}},
U5:{
"^":"mW;Q,a",
gu:function(a){var z=new H.SO(J.Nx(this.Q),this.a)
z.$builtinTypeInfo=this.$builtinTypeInfo
return z}},
SO:{
"^":"Ov;Q,a",
D:function(){for(var z=this.Q;z.D();)if(this.Mi(z.gk()))return!0
return!1},
gk:function(){return this.Q.gk()},
Mi:function(a){return this.a.$1(a)}}}],["","",,P,{
"^":"",
Ou:[function(a,b){return J.mG(a,b)},"$2","iv",4,0,4],
vJ:[function(a){return J.v1(a)},"$1","Ed",2,0,5],
EP:function(a,b,c){var z,y
if(P.nH(a)){if(b==="("&&c===")")return"(...)"
return b+"..."+c}z=[]
y=$.Ex()
y.push(a)
try{P.T4(a,z)}finally{y.pop()}y=new P.Rn(b)
y.We(z,", ")
y=y.Q+=c
return y.charCodeAt(0)==0?y:y},
WE:function(a,b,c){var z,y
if(P.nH(a))return b+"..."+c
z=new P.Rn(b)
y=$.Ex()
y.push(a)
try{z.We(a,", ")}finally{y.pop()}y=z
y.Q=y.gIN()+c
y=z.gIN()
return y.charCodeAt(0)==0?y:y},
nH:function(a){var z,y
for(z=0;y=$.Ex(),z<y.length;++z){y=y[z]
if(a==null?y==null:a===y)return!0}return!1},
T4:function(a,b){var z,y,x,w,v,u,t,s,r,q
z=a.gu(a)
y=0
x=0
while(!0){if(!(y<80||x<3))break
if(!z.D())return
w=H.d(z.gk())
b.push(w)
y+=w.length+2;++x}if(!z.D()){if(x<=5)return
v=b.pop()
u=b.pop()}else{t=z.gk();++x
if(!z.D()){if(x<=4){b.push(H.d(t))
return}v=H.d(t)
u=b.pop()
y+=v.length+2}else{s=z.gk();++x
for(;z.D();t=s,s=r){r=z.gk();++x
if(x>100){while(!0){if(!(y>75&&x>3))break
y-=b.pop().length+2;--x}b.push("...")
return}}u=H.d(t)
v=H.d(s)
y+=v.length+u.length+4}}if(x>b.length+2){y+=5
q="..."}else q=null
while(!0){if(!(y>80&&b.length>3))break
y-=b.pop().length+2
if(q==null){y+=5
q="..."}}if(q!=null)b.push(q)
b.push(u)
b.push(v)},
L:function(a,b,c,d,e){return H.J(new H.N5(0,null,null,null,null,null,0),[d,e])},
Ls:function(a,b,c,d){return H.J(new P.b6(0,null,null,null,null,null,0),[d])},
vW:function(a){var z,y,x
z={}
if(P.nH(a))return"{...}"
y=new P.Rn("")
try{$.Ex().push(a)
x=y
x.Q=x.gIN()+"{"
z.Q=!0
J.kH(a,new P.LG(z,y))
z=y
z.Q=z.gIN()+"}"}finally{$.Ex().pop()}z=y.gIN()
return z.charCodeAt(0)==0?z:z},
b6:{
"^":"u3;Q,a,b,c,d,e,f",
gu:function(a){var z=new P.zQ(this,this.f,null,null)
z.b=this.d
return z},
gv:function(a){return this.Q},
aN:function(a,b){var z,y
z=this.d
y=this.f
for(;z!=null;){b.$1(z.Q)
if(y!==this.f)throw H.b(P.a4(this))
z=z.a}},
gFV:function(a){var z=this.d
if(z==null)throw H.b(P.s("No elements"))
return z.Q},
h:function(a,b){var z,y
if(typeof b==="string"&&b!=="__proto__"){z=this.a
if(z==null){y=Object.create(null)
y["<non-identifier-key>"]=y
delete y["<non-identifier-key>"]
this.a=y
z=y}return this.bQ(z,b)}else return this.B7(b)},
B7:function(a){var z,y,x
z=this.c
if(z==null){z=P.T2()
this.c=z}y=this.rk(a)
x=z[y]
if(x==null)z[y]=[this.yo(a)]
else{if(this.DF(x,a)>=0)return!1
x.push(this.yo(a))}return!0},
Rz:function(a,b){if(typeof b==="string"&&b!=="__proto__")return this.H4(this.a,b)
else if(typeof b==="number"&&(b&0x3ffffff)===b)return this.H4(this.b,b)
else return this.qg(b)},
qg:function(a){var z,y,x
z=this.c
if(z==null)return!1
y=z[this.rk(a)]
x=this.DF(y,a)
if(x<0)return!1
this.GS(y.splice(x,1)[0])
return!0},
bQ:function(a,b){if(a[b]!=null)return!1
a[b]=this.yo(b)
return!0},
H4:function(a,b){var z
if(a==null)return!1
z=a[b]
if(z==null)return!1
this.GS(z)
delete a[b]
return!0},
yo:function(a){var z,y
z=new P.tj(a,null,null)
if(this.d==null){this.e=z
this.d=z}else{y=this.e
z.b=y
y.a=z
this.e=z}++this.Q
this.f=this.f+1&67108863
return z},
GS:function(a){var z,y
z=a.b
y=a.a
if(z==null)this.d=y
else z.a=y
if(y==null)this.e=z
else y.b=z;--this.Q
this.f=this.f+1&67108863},
rk:function(a){return J.v1(a)&0x3ffffff},
DF:function(a,b){var z,y,x
if(a==null)return-1
z=a.length
for(y=0;y<z;++y){x=a[y].Q
if(x==null?b==null:x===b)return y}return-1},
$iscX:1,
$ascX:null,
static:{T2:function(){var z=Object.create(null)
z["<non-identifier-key>"]=z
delete z["<non-identifier-key>"]
return z}}},
tj:{
"^":"a;Q,a,b"},
zQ:{
"^":"a;Q,a,b,c",
gk:function(){return this.c},
D:function(){var z=this.Q
if(this.a!==z.f)throw H.b(P.a4(z))
else{z=this.b
if(z==null){this.c=null
return!1}else{this.c=z.Q
this.b=z.a
return!0}}}},
u3:{
"^":"Vj;"},
mW:{
"^":"a;",
aN:function(a,b){var z
for(z=this.gu(this);z.D();)b.$1(z.gk())},
gv:function(a){var z,y
z=this.gu(this)
for(y=0;z.D();)++y
return y},
gFV:function(a){var z=this.gu(this)
if(!z.D())throw H.b(H.Wp())
return z.gk()},
Zv:function(a,b){var z,y,x
if(b<0)H.R(P.TE(b,0,null,"index",null))
for(z=this.gu(this),y=0;z.D();){x=z.gk()
if(b===y)return x;++y}throw H.b(P.Cf(b,this,"index",null,y))},
X:function(a){return P.EP(this,"(",")")},
$iscX:1,
$ascX:null},
ar:{
"^":"E9;"},
E9:{
"^":"a+lD;",
$iszM:1,
$aszM:null,
$iscX:1,
$ascX:null},
lD:{
"^":"a;",
gu:function(a){return new H.a7(a,this.gv(a),0,null)},
Zv:function(a,b){return this.p(a,b)},
aN:function(a,b){var z,y
z=this.gv(a)
for(y=0;y<z;++y){b.$1(this.p(a,y))
if(z!==this.gv(a))throw H.b(P.a4(a))}},
gl0:function(a){return this.gv(a)===0},
gor:function(a){return!this.gl0(a)},
gFV:function(a){if(this.gv(a)===0)throw H.b(H.Wp())
return this.p(a,0)},
ev:function(a,b){return H.J(new H.U5(a,b),[H.W8(a,"lD",0)])},
ez:function(a,b){return H.J(new H.A8(a,b),[null,null])},
tt:function(a,b){var z,y
if(b){z=H.J([],[H.W8(a,"lD",0)])
C.Nm.sv(z,this.gv(a))}else z=H.J(Array(this.gv(a)),[H.W8(a,"lD",0)])
for(y=0;y<this.gv(a);++y)z[y]=this.p(a,y)
return z},
br:function(a){return this.tt(a,!0)},
X:function(a){return P.WE(a,"[","]")},
$iszM:1,
$aszM:null,
$iscX:1,
$ascX:null},
LG:{
"^":"r;Q,a",
$2:function(a,b){var z,y
z=this.Q
if(!z.Q)this.a.Q+=", "
z.Q=!1
z=this.a
y=z.Q+=H.d(a)
z.Q=y+": "
z.Q+=H.d(b)}},
Ma:{
"^":"a;",
Ay:function(a,b){var z
for(z=new P.zQ(b,b.f,null,null),z.b=b.d;z.D();)this.h(0,z.c)},
X:function(a){return P.WE(this,"{","}")},
aN:function(a,b){var z
for(z=this.gu(this);z.D();)b.$1(z.c)},
zV:function(a,b){var z,y,x
z=this.gu(this)
if(!z.D())return""
y=new P.Rn("")
if(b===""){do y.Q+=H.d(z.c)
while(z.D())}else{y.Q=H.d(z.c)
for(;z.D();){y.Q+=b
y.Q+=H.d(z.c)}}x=y.Q
return x.charCodeAt(0)==0?x:x},
gFV:function(a){var z=this.gu(this)
if(!z.D())throw H.b(H.Wp())
return z.c},
Zv:function(a,b){var z,y,x
for(z=this.gu(this),y=0;z.D();){x=z.c
if(b===y)return x;++y}throw H.b(P.Cf(b,this,"index",null,y))},
$iscX:1,
$ascX:null},
Vj:{
"^":"Ma;"}}],["","",,P,{
"^":"",
Hp:function(a){return H.Fv(a)},
hl:function(a){if(typeof a==="number"||typeof a==="boolean"||null==a)return J.Lz(a)
if(typeof a==="string")return JSON.stringify(a)
return"Instance of '"+H.lh(a)+"'"},
ad:[function(a,b){return a==null?b==null:a===b},"$2","N3",4,0,6],
xv:[function(a){return H.CU(a)},"$1","J2",2,0,7],
z:function(a,b,c){var z,y
z=H.J([],[c])
for(y=J.Nx(a);y.D();)z.push(y.gk())
if(b)return z
z.fixed$length=Array
return z},
dH:function(a,b,c,d){var z,y
if(c){z=H.J([],[d])
C.Nm.sv(z,a)}else z=H.J(Array(a),[d])
for(y=0;y<a;++y)z[y]=b.$1(y)
return z},
CL:{
"^":"r;Q",
$2:function(a,b){var z=this.Q
if(z.a>0)z.Q.Q+=", "
P.Hp(a)}},
a2:{
"^":"a;"},
"+bool":0,
CP:{
"^":"lf;"},
"+double":0,
Ge:{
"^":"a;"},
LK:{
"^":"Ge;",
X:function(a){return"Throw of null."}},
AT:{
"^":"Ge;Q,a,b,c",
gZ2:function(){return"Invalid argument"+(!this.Q?"(s)":"")},
guF:function(){return""},
X:function(a){var z,y,x,w,v,u
z=this.b
y=z!=null?" ("+H.d(z)+")":""
z=this.c
x=z==null?"":": "+H.d(z)
w=this.gZ2()+y+x
if(!this.Q)return w
v=this.guF()
u=P.hl(this.a)
return w+v+": "+H.d(u)},
static:{p:function(a){return new P.AT(!1,null,null,a)},L3:function(a,b,c){return new P.AT(!0,a,b,c)}}},
bJ:{
"^":"AT;d,e,Q,a,b,c",
gZ2:function(){return"RangeError"},
guF:function(){var z,y,x
z=this.d
if(z==null){z=this.e
y=z!=null?": Not less than or equal to "+H.d(z):""}else{x=this.e
if(x==null)y=": Not greater than or equal to "+H.d(z)
else if(x>z)y=": Not in range "+H.d(z)+".."+H.d(x)+", inclusive"
else y=x<z?": Valid value range is empty":": Only valid value is "+H.d(z)}return y},
static:{D:function(a,b,c){return new P.bJ(null,null,!0,a,b,"Value not in range")},TE:function(a,b,c,d,e){return new P.bJ(b,c,!0,a,d,"Invalid value")}}},
eY:{
"^":"AT;d,e,Q,a,b,c",
gZ2:function(){return"RangeError"},
guF:function(){P.hl(this.d)
var z=": index should be less than "+this.e
return this.a<0?": index must not be negative":z},
static:{Cf:function(a,b,c,d,e){var z=e!=null?e:J.wS(b)
return new P.eY(b,z,!0,a,c,"Index out of range")}}},
ub:{
"^":"Ge;Q",
X:function(a){return"Unsupported operation: "+this.Q},
static:{f:function(a){return new P.ub(a)}}},
ds:{
"^":"Ge;Q",
X:function(a){var z=this.Q
return z!=null?"UnimplementedError: "+H.d(z):"UnimplementedError"},
static:{SY:function(a){return new P.ds(a)}}},
lj:{
"^":"Ge;Q",
X:function(a){return"Bad state: "+this.Q},
static:{s:function(a){return new P.lj(a)}}},
UV:{
"^":"Ge;Q",
X:function(a){var z=this.Q
if(z==null)return"Concurrent modification during iteration."
return"Concurrent modification during iteration: "+H.d(P.hl(z))+"."},
static:{a4:function(a){return new P.UV(a)}}},
k5:{
"^":"a;",
X:function(a){return"Out of Memory"},
$isGe:1},
VS:{
"^":"a;",
X:function(a){return"Stack Overflow"},
$isGe:1},
t7:{
"^":"Ge;Q",
X:function(a){return"Reading static variable '"+this.Q+"' during its initialization"}},
HG:{
"^":"a;Q",
X:function(a){return"Exception: "+this.Q}},
aE:{
"^":"a;Q,a,b",
X:function(a){var z,y
z=""!==this.Q?"FormatException: "+this.Q:"FormatException"
y=this.a
if(y.length>78)y=C.xB.Nj(y,0,75)+"..."
return z+"\n"+y}},
N:{
"^":"a;Q",
X:function(a){return"Expando:"+H.d(this.Q)},
p:function(a,b){var z=H.of(b,"expando$values")
return z==null?null:H.of(z,this.Ux())},
q:function(a,b,c){var z=H.of(b,"expando$values")
if(z==null){z=new P.a()
H.aw(b,"expando$values",z)}H.aw(z,this.Ux(),c)},
Ux:function(){var z,y
z=H.of(this,"expando$key")
if(z==null){y=$.Ss
$.Ss=y+1
z="expando$key$"+y
H.aw(this,"expando$key",z)}return z}},
P:{
"^":"lf;"},
"+int":0,
cX:{
"^":"a;",
$ascX:null},
Ov:{
"^":"a;"},
zM:{
"^":"a;",
$aszM:null,
$iscX:1},
"+List":0,
c8:{
"^":"a;",
X:function(a){return"null"}},
"+Null":0,
lf:{
"^":"a;"},
"+num":0,
a:{
"^":";",
m:function(a,b){return this===b},
giO:function(a){return H.wP(this)},
X:function(a){return H.a5(this)}},
I:{
"^":"a;"},
"+String":0,
Rn:{
"^":"a;IN:Q<",
We:function(a,b){var z=J.Nx(a)
if(!z.D())return
if(b.length===0){do this.Q+=H.d(z.gk())
while(z.D())}else{this.Q+=H.d(z.gk())
for(;z.D();){this.Q+=b
this.Q+=H.d(z.gk())}}},
X:function(a){var z=this.Q
return z.charCodeAt(0)==0?z:z}},
wv:{
"^":"a;"}}],["","",,W,{
"^":"",
ZD:function(a){return a.replace(/^-ms-/,"ms-").replace(/-([\da-z])/ig,C.Vu)},
Pv:function(a){if(a==null)return
return W.P1(a)},
qE:{
"^":"cv;",
"%":"HTMLAppletElement|HTMLAudioElement|HTMLBRElement|HTMLBaseElement|HTMLBodyElement|HTMLCanvasElement|HTMLContentElement|HTMLDListElement|HTMLDataListElement|HTMLDetailsElement|HTMLDialogElement|HTMLDirectoryElement|HTMLDivElement|HTMLEmbedElement|HTMLFontElement|HTMLFormElement|HTMLFrameElement|HTMLFrameSetElement|HTMLHRElement|HTMLHeadElement|HTMLHeadingElement|HTMLHtmlElement|HTMLIFrameElement|HTMLImageElement|HTMLKeygenElement|HTMLLabelElement|HTMLLegendElement|HTMLLinkElement|HTMLMapElement|HTMLMarqueeElement|HTMLMediaElement|HTMLMetaElement|HTMLModElement|HTMLOListElement|HTMLObjectElement|HTMLParagraphElement|HTMLPictureElement|HTMLPreElement|HTMLQuoteElement|HTMLScriptElement|HTMLShadowElement|HTMLSourceElement|HTMLSpanElement|HTMLStyleElement|HTMLTableCaptionElement|HTMLTableCellElement|HTMLTableColElement|HTMLTableDataCellElement|HTMLTableElement|HTMLTableHeaderCellElement|HTMLTableRowElement|HTMLTableSectionElement|HTMLTemplateElement|HTMLTitleElement|HTMLUListElement|HTMLUnknownElement|HTMLVideoElement|PluginPlaceholderElement;HTMLElement"},
Gh:{
"^":"qE;",
X:function(a){return String(a)},
"%":"HTMLAnchorElement"},
fY:{
"^":"qE;",
X:function(a){return String(a)},
"%":"HTMLAreaElement"},
IF:{
"^":"qE;M:value=",
"%":"HTMLButtonElement"},
oJ:{
"^":"BV;",
Qe:function(a,b){var z,y
z=$.pJ()
y=z[b]
if(typeof y==="string")return y
y=W.ZD(b) in a?b:C.xB.g(P.O2(),b)
z[b]=y
return y},
Dg:function(a,b,c,d){if(c==null)c=""
if(d==null)d=""
a.setProperty(b,c,d)},
"%":"CSS2Properties|CSSStyleDeclaration|MSStyleCSSProperties"},
BV:{
"^":"Gv+RE;"},
RE:{
"^":"a;"},
QF:{
"^":"KV;",
Wk:function(a,b){return a.querySelector(b)},
Md:function(a,b){return new W.wz(a.querySelectorAll(b))},
"%":"Document|HTMLDocument|XMLDocument"},
hs:{
"^":"KV;",
gwd:function(a){if(a._docChildren==null)a._docChildren=H.J(new P.D7(a,new W.e7(a)),[null])
return a._docChildren},
Md:function(a,b){return new W.wz(a.querySelectorAll(b))},
Wk:function(a,b){return a.querySelector(b)},
"%":"DocumentFragment|ShadowRoot"},
Nh:{
"^":"Gv;",
X:function(a){return String(a)},
"%":"DOMException"},
BE:{
"^":"zX;M:value=",
"%":"DOMSettableTokenList"},
zX:{
"^":"Gv;",
"%":";DOMTokenList"},
VG:{
"^":"ar;Q,a",
gl0:function(a){return this.Q.firstElementChild==null},
gv:function(a){return this.a.length},
p:function(a,b){return this.a[b]},
q:function(a,b,c){this.Q.replaceChild(c,this.a[b])},
h:function(a,b){this.Q.appendChild(b)
return b},
gu:function(a){var z=this.br(this)
return new J.m1(z,z.length,0,null)},
gFV:function(a){var z=this.Q.firstElementChild
if(z==null)throw H.b(P.s("No elements"))
return z},
$asar:function(){return[W.cv]},
$aszM:function(){return[W.cv]},
$ascX:function(){return[W.cv]}},
wz:{
"^":"ar;Q",
gv:function(a){return this.Q.length},
p:function(a,b){return this.Q[b]},
q:function(a,b,c){throw H.b(P.f("Cannot modify list"))},
gFV:function(a){return C.t5.gFV(this.Q)},
gDD:function(a){return W.TT(this)},
$asar:$.Cq,
$aszM:$.Cq,
$ascX:$.Cq,
$iszM:1,
$iscX:1},
cv:{
"^":"KV;",
gwd:function(a){return new W.VG(a,a.children)},
Md:function(a,b){return new W.wz(a.querySelectorAll(b))},
gDD:function(a){return new W.I4(a)},
X:function(a){return a.localName},
Wk:function(a,b){return a.querySelector(b)},
$iscv:1,
$isa:1,
"%":";Element"},
D0:{
"^":"Gv;",
"%":";EventTarget"},
as:{
"^":"qE;P9:elements=",
"%":"HTMLFieldSetElement"},
xn:{
"^":"ec;",
gv:function(a){return a.length},
p:function(a,b){if(b>>>0!==b||b>=a.length)throw H.b(P.Cf(b,a,null,null,null))
return a[b]},
q:function(a,b,c){throw H.b(P.f("Cannot assign element of immutable List."))},
gFV:function(a){if(a.length>0)return a[0]
throw H.b(P.s("No elements"))},
Zv:function(a,b){return a[b]},
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]},
$isXj:1,
"%":"HTMLCollection|HTMLFormControlsCollection|HTMLOptionsCollection"},
RA:{
"^":"Gv+lD;",
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]}},
ec:{
"^":"RA+Gm;",
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]}},
Mi:{
"^":"qE;M:value=",
$iscv:1,
"%":"HTMLInputElement"},
Gx:{
"^":"qE;M:value=",
"%":"HTMLLIElement"},
ZY:{
"^":"qE;ph:label=",
"%":"HTMLMenuElement"},
DH:{
"^":"qE;ph:label=",
"%":"HTMLMenuItemElement"},
Qb:{
"^":"qE;M:value=",
"%":"HTMLMeterElement"},
e7:{
"^":"ar;Q",
gFV:function(a){var z=this.Q.firstChild
if(z==null)throw H.b(P.s("No elements"))
return z},
q:function(a,b,c){var z=this.Q
z.replaceChild(c,z.childNodes[b])},
gu:function(a){return C.t5.gu(this.Q.childNodes)},
gv:function(a){return this.Q.childNodes.length},
p:function(a,b){return this.Q.childNodes[b]},
$asar:function(){return[W.KV]},
$aszM:function(){return[W.KV]},
$ascX:function(){return[W.KV]}},
KV:{
"^":"D0;eT:parentElement=,a4:textContent}",
Tk:function(a,b){var z,y
try{z=a.parentNode
J.EE(z,b,a)}catch(y){H.Ru(y)}return a},
X:function(a){var z=a.nodeValue
return z==null?this.VE(a):z},
Y:function(a,b){return a.appendChild(b)},
AS:function(a,b,c){return a.replaceChild(b,c)},
$isa:1,
"%":"CDATASection|CharacterData|Comment|DocumentType|ProcessingInstruction|Text;Node"},
BH:{
"^":"x5;",
gv:function(a){return a.length},
p:function(a,b){if(b>>>0!==b||b>=a.length)throw H.b(P.Cf(b,a,null,null,null))
return a[b]},
q:function(a,b,c){throw H.b(P.f("Cannot assign element of immutable List."))},
gFV:function(a){if(a.length>0)return a[0]
throw H.b(P.s("No elements"))},
Zv:function(a,b){return a[b]},
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]},
$isXj:1,
"%":"NodeList|RadioNodeList"},
nN:{
"^":"Gv+lD;",
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]}},
x5:{
"^":"nN+Gm;",
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]}},
l9:{
"^":"qE;ph:label=",
"%":"HTMLOptGroupElement"},
Ql:{
"^":"qE;ph:label=,M:value=",
"%":"HTMLOptionElement"},
wL:{
"^":"qE;M:value=",
"%":"HTMLOutputElement"},
HD:{
"^":"qE;M:value=",
"%":"HTMLParamElement"},
KR:{
"^":"qE;M:value=",
"%":"HTMLProgressElement"},
lp:{
"^":"qE;M:value=",
"%":"HTMLSelectElement"},
FB:{
"^":"qE;M:value=",
"%":"HTMLTextAreaElement"},
Cw:{
"^":"qE;ph:label=",
"%":"HTMLTrackElement"},
u9:{
"^":"D0;",
geT:function(a){return W.Pv(a.parent)},
"%":"DOMWindow|Window"},
UM:{
"^":"KV;M:value=",
sa4:function(a,b){a.textContent=b},
"%":"Attr"},
rh:{
"^":"HR;",
gv:function(a){return a.length},
p:function(a,b){if(b>>>0!==b||b>=a.length)throw H.b(P.Cf(b,a,null,null,null))
return a[b]},
q:function(a,b,c){throw H.b(P.f("Cannot assign element of immutable List."))},
gFV:function(a){if(a.length>0)return a[0]
throw H.b(P.s("No elements"))},
Zv:function(a,b){return a[b]},
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]},
$isXj:1,
"%":"MozNamedAttrMap|NamedNodeMap"},
yo:{
"^":"Gv+lD;",
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]}},
HR:{
"^":"yo+Gm;",
$iszM:1,
$aszM:function(){return[W.KV]},
$iscX:1,
$ascX:function(){return[W.KV]}},
nF:{
"^":"As;Q,a",
DG:function(){var z=P.Ls(null,null,null,P.I)
C.Nm.aN(this.a,new W.Si(z))
return z},
p5:function(a){var z,y
z=a.zV(0," ")
for(y=this.Q,y=y.gu(y);y.D();)y.c.className=z},
OS:function(a){C.Nm.aN(this.a,new W.vf(a))},
Rz:function(a,b){return C.Nm.es(this.a,!1,new W.Fc(b))},
static:{TT:function(a){return new W.nF(a,a.ez(a,new W.or()).br(0))}}},
or:{
"^":"r;",
$1:function(a){return J.pP(a)}},
Si:{
"^":"r;Q",
$1:function(a){return this.Q.Ay(0,a.DG())}},
vf:{
"^":"r;Q",
$1:function(a){return a.OS(this.Q)}},
Fc:{
"^":"r;Q",
$2:function(a,b){return b.Rz(0,this.Q)||a}},
I4:{
"^":"As;Q",
DG:function(){var z,y,x
z=P.Ls(null,null,null,P.I)
for(y=this.Q.className.split(" "),y=new J.m1(y,y.length,0,null);y.D();){x=J.rr(y.c)
if(x.length!==0)z.h(0,x)}return z},
p5:function(a){this.Q.className=a.zV(0," ")},
gv:function(a){return this.Q.classList.length},
h:function(a,b){var z,y
z=this.Q.classList
y=z.contains(b)
z.add(b)
return!y},
Rz:function(a,b){var z,y,x
z=this.Q.classList
y=z.contains(b)
z.remove(b)
x=y
return x}},
Gm:{
"^":"a;",
gu:function(a){return new W.W9(a,this.gv(a),-1,null)},
$iszM:1,
$aszM:null,
$iscX:1,
$ascX:null},
W9:{
"^":"a;Q,a,b,c",
D:function(){var z,y
z=this.b+1
y=this.a
if(z<y){this.c=J.Tf(this.Q,z)
this.b=z
return!0}this.c=null
this.b=y
return!1},
gk:function(){return this.c}},
dW:{
"^":"a;Q",
geT:function(a){return W.P1(this.Q.parent)},
static:{P1:function(a){if(a===window)return a
else return new W.dW(a)}}}}],["","",,P,{
"^":"",
jw:{
"^":"d5;x=,y=",
"%":"SVGFEBlendElement"},
lv:{
"^":"d5;x=,y=",
"%":"SVGFEColorMatrixElement"},
pf:{
"^":"d5;x=,y=",
"%":"SVGFEComponentTransferElement"},
py:{
"^":"d5;x=,y=",
"%":"SVGFECompositeElement"},
W1:{
"^":"d5;x=,y=",
"%":"SVGFEConvolveMatrixElement"},
zo:{
"^":"d5;x=,y=",
"%":"SVGFEDiffuseLightingElement"},
wf:{
"^":"d5;x=,y=",
"%":"SVGFEDisplacementMapElement"},
ih:{
"^":"d5;x=,y=",
"%":"SVGFEFloodElement"},
tk:{
"^":"d5;x=,y=",
"%":"SVGFEGaussianBlurElement"},
me:{
"^":"d5;x=,y=",
"%":"SVGFEImageElement"},
oB:{
"^":"d5;x=,y=",
"%":"SVGFEMergeElement"},
yu:{
"^":"d5;x=,y=",
"%":"SVGFEMorphologyElement"},
MI:{
"^":"d5;Z:dx=,qV:dy=,x=,y=",
"%":"SVGFEOffsetElement"},
Ub:{
"^":"d5;x=,y=",
"%":"SVGFEPointLightElement"},
bM:{
"^":"d5;x=,y=",
"%":"SVGFESpecularLightingElement"},
eW:{
"^":"d5;x=,y=",
"%":"SVGFESpotLightElement"},
Qy:{
"^":"d5;x=,y=",
"%":"SVGFETileElement"},
ju:{
"^":"d5;x=,y=",
"%":"SVGFETurbulenceElement"},
OE:{
"^":"d5;x=,y=",
"%":"SVGFilterElement"},
q8:{
"^":"tp;x=,y=",
"%":"SVGForeignObjectElement"},
d0:{
"^":"tp;",
"%":"SVGCircleElement|SVGEllipseElement|SVGLineElement|SVGPathElement|SVGPolygonElement|SVGPolylineElement;SVGGeometryElement"},
tp:{
"^":"d5;",
"%":"SVGAElement|SVGClipPathElement|SVGDefsElement|SVGGElement|SVGSwitchElement;SVGGraphicsElement"},
rE:{
"^":"tp;x=,y=",
"%":"SVGImageElement"},
NB:{
"^":"d5;x=,y=",
"%":"SVGMaskElement"},
Gr:{
"^":"d5;x=,y=",
"%":"SVGPatternElement"},
jr:{
"^":"d0;x=,y=",
"%":"SVGRectElement"},
O7:{
"^":"As;Q",
DG:function(){var z,y,x,w
z=this.Q.getAttribute("class")
y=P.Ls(null,null,null,P.I)
if(z==null)return y
for(x=z.split(" "),x=new J.m1(x,x.length,0,null);x.D();){w=J.rr(x.c)
if(w.length!==0)y.h(0,w)}return y},
p5:function(a){this.Q.setAttribute("class",a.zV(0," "))}},
d5:{
"^":"cv;",
gDD:function(a){return new P.O7(a)},
gwd:function(a){return H.J(new P.D7(a,new W.e7(a)),[W.cv])},
"%":"SVGAltGlyphDefElement|SVGAltGlyphItemElement|SVGAnimateElement|SVGAnimateMotionElement|SVGAnimateTransformElement|SVGAnimationElement|SVGComponentTransferFunctionElement|SVGCursorElement|SVGDescElement|SVGDiscardElement|SVGFEDistantLightElement|SVGFEDropShadowElement|SVGFEFuncAElement|SVGFEFuncBElement|SVGFEFuncGElement|SVGFEFuncRElement|SVGFEMergeNodeElement|SVGFontElement|SVGFontFaceElement|SVGFontFaceFormatElement|SVGFontFaceNameElement|SVGFontFaceSrcElement|SVGFontFaceUriElement|SVGGlyphElement|SVGGlyphRefElement|SVGGradientElement|SVGHKernElement|SVGLinearGradientElement|SVGMPathElement|SVGMarkerElement|SVGMetadataElement|SVGMissingGlyphElement|SVGRadialGradientElement|SVGScriptElement|SVGSetElement|SVGStopElement|SVGStyleElement|SVGSymbolElement|SVGTitleElement|SVGVKernElement|SVGViewElement;SVGElement"},
hy:{
"^":"tp;x=,y=",
"%":"SVGSVGElement"},
qF:{
"^":"tp;",
"%":"SVGTextPathElement;SVGTextContentElement"},
Eo:{
"^":"qF;Z:dx=,qV:dy=,x=,y=",
"%":"SVGAltGlyphElement|SVGTSpanElement|SVGTextElement|SVGTextPositioningElement"},
ox:{
"^":"tp;x=,y=",
"%":"SVGUseElement"}}],["","",,P,{
"^":""}],["","",,P,{
"^":"",
C:function(a,b){var z
if(a>b)return b
if(a<b)return a
if(typeof b==="number"){if(typeof a==="number")if(a===0)return(a+b)*a*b
if(a===0)z=b===0?1/b<0:b<0
else z=!1
if(z||isNaN(b))return b
return a}return a},
u:function(a,b){if(a>b)return a
if(a<b)return b
if(typeof b==="number"){if(typeof a==="number")if(a===0)return a+b
if(isNaN(b))return b
return a}if(b===0&&C.CD.gzP(a))return b
return a}}],["","",,P,{
"^":"",
dg:function(){var z=$.az
if(z==null){z=J.Vw(window.navigator.userAgent,"Opera",0)
$.az=z}return z},
O2:function(){var z,y
z=$.aj
if(z!=null)return z
y=$.w5
if(y==null){y=J.Vw(window.navigator.userAgent,"Firefox",0)
$.w5=y}if(y)z="-moz-"
else{y=$.EM
if(y==null){y=!P.dg()&&J.Vw(window.navigator.userAgent,"Trident/",0)
$.EM=y}if(y)z="-ms-"
else z=P.dg()?"-o-":"-webkit-"}$.aj=z
return z},
As:{
"^":"a;",
VL:function(a){if($.pq().a.test(H.Yx(a)))return a
throw H.b(P.L3(a,"value","Not a valid class token"))},
X:function(a){return this.DG().zV(0," ")},
gu:function(a){var z,y
z=this.DG()
y=new P.zQ(z,z.f,null,null)
y.b=z.d
return y},
aN:function(a,b){this.DG().aN(0,b)},
gv:function(a){return this.DG().Q},
h:function(a,b){this.VL(b)
return this.OS(new P.GE(b))},
Rz:function(a,b){var z,y
this.VL(b)
z=this.DG()
y=z.Rz(0,b)
this.p5(z)
return y},
gFV:function(a){var z=this.DG()
return z.gFV(z)},
Zv:function(a,b){return this.DG().Zv(0,b)},
OS:function(a){var z,y
z=this.DG()
y=a.$1(z)
this.p5(z)
return y},
$iscX:1,
$ascX:function(){return[P.I]}},
GE:{
"^":"r;Q",
$1:function(a){return a.h(0,this.Q)}},
D7:{
"^":"ar;Q,a",
gd3:function(){var z=this.a
return P.z(z.ev(z,new P.Zf()),!0,H.Kp(this,0))},
aN:function(a,b){C.Nm.aN(this.gd3(),b)},
q:function(a,b,c){J.ZP(this.gd3()[b],c)},
h:function(a,b){this.a.Q.appendChild(b)},
gv:function(a){return this.gd3().length},
p:function(a,b){return this.gd3()[b]},
gu:function(a){var z=this.gd3()
return new J.m1(z,z.length,0,null)}},
Zf:{
"^":"r;",
$1:function(a){return!!J.t(a).$iscv}}}],]
setupProgram(dart)
J.Qc=function(a){if(typeof a=="number")return J.F.prototype
if(typeof a=="string")return J.E.prototype
if(a==null)return a
if(!(a instanceof P.a))return J.kd.prototype
return a}
J.U6=function(a){if(typeof a=="string")return J.E.prototype
if(a==null)return a
if(a.constructor==Array)return J.G.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.ks(a)}
J.Y=function(a){if(a==null)return a
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.ks(a)}
J.rY=function(a){if(typeof a=="string")return J.E.prototype
if(a==null)return a
if(!(a instanceof P.a))return J.kd.prototype
return a}
J.t=function(a){if(typeof a=="number"){if(Math.floor(a)==a)return J.im.prototype
return J.VA.prototype}if(typeof a=="string")return J.E.prototype
if(a==null)return J.PE.prototype
if(typeof a=="boolean")return J.yE.prototype
if(a.constructor==Array)return J.G.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.ks(a)}
J.w1=function(a){if(a==null)return a
if(a.constructor==Array)return J.G.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.ks(a)}
J.C0=function(a){return J.Y(a).gy(a)}
J.C7=function(a,b,c){if((a.constructor==Array||H.wV(a,a[init.dispatchPropertyName]))&&!a.immutable$list&&b>>>0===b&&b<a.length)return a[b]=c
return J.w1(a).q(a,b,c)}
J.EE=function(a,b,c){return J.Y(a).AS(a,b,c)}
J.Lz=function(a){return J.t(a).X(a)}
J.MK=function(a,b){return J.Y(a).Md(a,b)}
J.Nx=function(a){return J.w1(a).gu(a)}
J.OG=function(a){return J.Y(a).gwd(a)}
J.RG=function(a,b){return J.Y(a).Y(a,b)}
J.Rd=function(a){return J.Y(a).gx(a)}
J.SW=function(a){return J.Y(a).gM(a)}
J.Tf=function(a,b){if(a.constructor==Array||typeof a=="string"||H.wV(a,a[init.dispatchPropertyName]))if(b>>>0===b&&b<a.length)return a[b]
return J.U6(a).p(a,b)}
J.Vw=function(a,b,c){return J.U6(a).Is(a,b,c)}
J.ZP=function(a,b){return J.Y(a).Tk(a,b)}
J.c1=function(a,b){return J.Y(a).Wk(a,b)}
J.i4=function(a,b){return J.w1(a).Zv(a,b)}
J.kH=function(a,b){return J.w1(a).aN(a,b)}
J.lX=function(a,b){if(typeof a=="number"&&typeof b=="number")return a*b
return J.Qc(a).R(a,b)}
J.mG=function(a,b){if(a==null)return b==null
if(typeof a!="object")return b!=null&&a===b
return J.t(a).m(a,b)}
J.pO=function(a){return J.U6(a).gor(a)}
J.pP=function(a){return J.Y(a).gDD(a)}
J.rr=function(a){return J.rY(a).bS(a)}
J.t3=function(a,b){return J.Y(a).sa4(a,b)}
J.tw=function(a){return J.Y(a).gqV(a)}
J.v1=function(a){return J.t(a).giO(a)}
J.wS=function(a){return J.U6(a).gv(a)}
J.zd=function(a){return J.Y(a).gZ(a)}
I.uL=function(a){a.immutable$list=Array
a.fixed$length=Array
return a}
C.rd=W.oJ.prototype
C.Nm=J.G.prototype
C.ON=J.VA.prototype
C.jn=J.im.prototype
C.CD=J.F.prototype
C.xB=J.E.prototype
C.t5=W.BH.prototype
C.ZQ=J.iC.prototype
C.vB=J.kd.prototype
C.Eq=new P.k5()
C.Mc=function(hooks) {
  if (typeof dartExperimentalFixupGetTag != "function") return hooks;
  hooks.getTag = dartExperimentalFixupGetTag(hooks.getTag);
}
C.lR=function(hooks) {
  var userAgent = typeof navigator == "object" ? navigator.userAgent : "";
  if (userAgent.indexOf("Firefox") == -1) return hooks;
  var getTag = hooks.getTag;
  var quickMap = {
    "BeforeUnloadEvent": "Event",
    "DataTransfer": "Clipboard",
    "GeoGeolocation": "Geolocation",
    "Location": "!Location",
    "WorkerMessageEvent": "MessageEvent",
    "XMLDocument": "!Document"};
  function getTagFirefox(o) {
    var tag = getTag(o);
    return quickMap[tag] || tag;
  }
  hooks.getTag = getTagFirefox;
}
C.w2=function getTagFallback(o) {
  var constructor = o.constructor;
  if (typeof constructor == "function") {
    var name = constructor.name;
    if (typeof name == "string" &&
        name.length > 2 &&
        name !== "Object" &&
        name !== "Function.prototype") {
      return name;
    }
  }
  var s = Object.prototype.toString.call(o);
  return s.substring(8, s.length - 1);
}
C.XQ=function(hooks) { return hooks; }

C.ur=function(getTagFallback) {
  return function(hooks) {
    if (typeof navigator != "object") return hooks;
    var ua = navigator.userAgent;
    if (ua.indexOf("DumpRenderTree") >= 0) return hooks;
    if (ua.indexOf("Chrome") >= 0) {
      function confirm(p) {
        return typeof window == "object" && window[p] && window[p].name == p;
      }
      if (confirm("Window") && confirm("HTMLElement")) return hooks;
    }
    hooks.getTag = getTagFallback;
  };
}
C.Jh=function(hooks) {
  var userAgent = typeof navigator == "object" ? navigator.userAgent : "";
  if (userAgent.indexOf("Trident/") == -1) return hooks;
  var getTag = hooks.getTag;
  var quickMap = {
    "BeforeUnloadEvent": "Event",
    "DataTransfer": "Clipboard",
    "HTMLDDElement": "HTMLElement",
    "HTMLDTElement": "HTMLElement",
    "HTMLPhraseElement": "HTMLElement",
    "Position": "Geoposition"
  };
  function getTagIE(o) {
    var tag = getTag(o);
    var newTag = quickMap[tag];
    if (newTag) return newTag;
    if (tag == "Object") {
      if (window.DataView && (o instanceof window.DataView)) return "DataView";
    }
    return tag;
  }
  function prototypeForTagIE(tag) {
    var constructor = window[tag];
    if (constructor == null) return null;
    return constructor.prototype;
  }
  hooks.getTag = getTagIE;
  hooks.prototypeForTag = prototypeForTagIE;
}
C.M1=function() {
  function typeNameInChrome(o) {
    var constructor = o.constructor;
    if (constructor) {
      var name = constructor.name;
      if (name) return name;
    }
    var s = Object.prototype.toString.call(o);
    return s.substring(8, s.length - 1);
  }
  function getUnknownTag(object, tag) {
    if (/^HTML[A-Z].*Element$/.test(tag)) {
      var name = Object.prototype.toString.call(object);
      if (name == "[object Object]") return null;
      return "HTMLElement";
    }
  }
  function getUnknownTagGenericBrowser(object, tag) {
    if (self.HTMLElement && object instanceof HTMLElement) return "HTMLElement";
    return getUnknownTag(object, tag);
  }
  function prototypeForTag(tag) {
    if (typeof window == "undefined") return null;
    if (typeof window[tag] == "undefined") return null;
    var constructor = window[tag];
    if (typeof constructor != "function") return null;
    return constructor.prototype;
  }
  function discriminator(tag) { return null; }
  var isBrowser = typeof navigator == "object";
  return {
    getTag: typeNameInChrome,
    getUnknownTag: isBrowser ? getUnknownTagGenericBrowser : getUnknownTag,
    prototypeForTag: prototypeForTag,
    discriminator: discriminator };
}
C.hQ=function(hooks) {
  var getTag = hooks.getTag;
  var prototypeForTag = hooks.prototypeForTag;
  function getTagFixed(o) {
    var tag = getTag(o);
    if (tag == "Document") {
      if (!!o.xmlVersion) return "!Document";
      return "!HTMLDocument";
    }
    return tag;
  }
  function prototypeForTagFixed(tag) {
    if (tag == "Document") return null;
    return prototypeForTag(tag);
  }
  hooks.getTag = getTagFixed;
  hooks.prototypeForTag = prototypeForTagFixed;
}
C.Vu=function(_, letter) { return letter.toUpperCase(); }
C.nx=I.uL([0,0,0,0])
C.uv=I.uL(["#C5D9FB","#4184F3","#2955C5"])
C.An=I.uL(["#F3C6C2","#DB4437","#A52714"])
C.Pa=I.uL(["#FBE7B1","#F4B400","#EF9200"])
C.hp=I.uL(["#B6E0CC","#0F9D58","#0A7F42"])
C.jG=I.uL(["#E0BDE6","#AA46BB","#691A99"])
C.ue=I.uL(["#B1EAF1","#00ABC0","#00828E"])
C.WJ=I.uL(["#FFCBBB","#FF6F42","#E54918"])
C.UY=I.uL(["#EFF3C2","#9D9C23","#817616"])
C.CS=I.uL(["#C4C9E8","#5B6ABF","#3848AA"])
C.nd=I.uL(["#F7BACF","#EF6191","#E81D62"])
C.AC=I.uL(["#B1DEDA","#00786A","#004C3F"])
C.dO=I.uL(["#F38EB0","#C1175A","#870D4E"])
C.VK=I.uL([C.uv,C.An,C.Pa,C.hp,C.jG,C.ue,C.WJ,C.UY,C.CS,C.nd,C.AC,C.dO])
C.Sj=I.uL(["svg","xhtml","xlink","xml","xmlns"])
C.tQ=new H.LP(5,{svg:"http://www.w3.org/2000/svg",xhtml:"http://www.w3.org/1999/xhtml",xlink:"http://www.w3.org/1999/xlink",xml:"http://www.w3.org/XML/1998/namespace",xmlns:"http://www.w3.org/2000/xmlns/"},C.Sj)
{init.isHunkLoaded=function(a){return!!$dart_deferred_initializers[a]}
init.deferredInitialized=new Object(null)
init.isHunkInitialized=function(a){return init.deferredInitialized[a]}
init.initializeLoadedHunk=function(a){$dart_deferred_initializers[a](S0,$)
init.deferredInitialized[a]=true}}init.deferredLibraryUris={}
init.deferredLibraryHashes={}
$.yj=0
$.mJ=null
$.P4=null
$.NF=null
$.TX=null
$.x7=null
$.nw=null
$.vv=null
$.Bv=null
$.ot=2
$.dv=4
$.ha=256
$.o6=512
$.Ss=0
$.az=null
$.EM=null
$.w5=null
$.PN=null
$.aj=null
;(function(a){var z=3
for(var y=0;y<a.length;y+=z){var x=a[y]
var w=a[y+1]
var v=a[y+2]
I.$lazy(x,w,v)}})(["lm","WD",function(){return H.cM(H.S7({toString:function(){return"$receiver$"}}))},"k1","OI",function(){return H.cM(H.S7({$method$:null,toString:function(){return"$receiver$"}}))},"Re","PH",function(){return H.cM(H.S7(null))},"fN","D1",function(){return H.cM(function(){var $argumentsExpr$='$arguments$'
try{null.$method$($argumentsExpr$)}catch(z){return z.message}}())},"qi","rx",function(){return H.cM(H.S7(void 0))},"rZ","Kr",function(){return H.cM(function(){var $argumentsExpr$='$arguments$'
try{(void 0).$method$($argumentsExpr$)}catch(z){return z.message}}())},"BX","zO",function(){return H.cM(H.Mj(null))},"tt","Bi",function(){return H.cM(function(){try{null.$method$}catch(z){return z.message}}())},"dt","eA",function(){return H.cM(H.Mj(void 0))},"A7","ko",function(){return H.cM(function(){try{(void 0).$method$}catch(z){return z.message}}())},"nM","Ex",function(){return[]},"fd","pJ",function(){return{}},"GA","pq",function(){return new H.VR("^\\S+$",H.v4("^\\S+$",!1,!0,!1),null,null)}])

init.metadata=[];init.types=[{func:"",void:true,args:[Q.Gn]},{func:"",ret:P.zM,args:[Q.xT]},{func:"",ret:P.lf,args:[Q.xT]},{func:"",ret:P.P,args:[Q.xT,Q.xT]},{func:"",ret:P.a2,args:[,,]},{func:"",ret:P.P,args:[,]},{func:"",ret:P.a2,args:[P.a,P.a]},{func:"",ret:P.P,args:[P.a]},];$=null
I = I.$finishIsolateConstructor(I)
$=new I()
function convertToFastObject(a){function MyClass(){}MyClass.prototype=a
new MyClass()
return a}
function convertToSlowObject(a){a.__MAGIC_SLOW_PROPERTY=1
delete a.__MAGIC_SLOW_PROPERTY
return a}
A = convertToFastObject(A)
B = convertToFastObject(B)
C = convertToFastObject(C)
D = convertToFastObject(D)
E = convertToFastObject(E)
F = convertToFastObject(F)
G = convertToFastObject(G)
H = convertToFastObject(H)
J = convertToFastObject(J)
K = convertToFastObject(K)
L = convertToFastObject(L)
M = convertToFastObject(M)
N = convertToFastObject(N)
O = convertToFastObject(O)
P = convertToFastObject(P)
Q = convertToFastObject(Q)
R = convertToFastObject(R)
S = convertToFastObject(S)
T = convertToFastObject(T)
U = convertToFastObject(U)
V = convertToFastObject(V)
W = convertToFastObject(W)
X = convertToFastObject(X)
Y = convertToFastObject(Y)
Z = convertToFastObject(Z)
function init(){I.p=Object.create(null)
init.allClasses=Object.create(null)
init.getTypeFromName=function(a){return init.allClasses[a]}
init.interceptorsByTag=Object.create(null)
init.leafTags=Object.create(null)
init.finishedClasses=Object.create(null)
I.$lazy=function(a,b,c,d,e){if(!init.lazies)init.lazies=Object.create(null)
init.lazies[a]=b
e=e||I.p
var z={}
var y={}
e[a]=z
e[b]=function(){var x=this[a]
try{if(x===z){this[a]=y
try{x=this[a]=c()}finally{if(x===z)this[a]=null}}else if(x===y)H.eQ(d||a)
return x}finally{this[b]=function(){return this[a]}}}}
I.$finishIsolateConstructor=function(a){var z=a.p
function Isolate(){var y=Object.keys(z)
for(var x=0;x<y.length;x++){var w=y[x]
this[w]=z[w]}var v=init.lazies
var u=v?Object.keys(v):[]
for(var x=0;x<u.length;x++)this[v[u[x]]]=null
function ForceEfficientMap(){}ForceEfficientMap.prototype=this
new ForceEfficientMap()
for(var x=0;x<u.length;x++){var t=v[u[x]]
this[t]=z[t]}}Isolate.prototype=a.prototype
Isolate.prototype.constructor=Isolate
Isolate.p=z
Isolate.uL=a.uL
return Isolate}}
!function(){function intern(a){var u={}
u[a]=1
return Object.keys(convertToFastObject(u))[0]}init.getIsolateTag=function(a){return intern("___dart_"+a+init.isolateTag)}
var z="___dart_isolate_tags_"
var y=Object[z]||(Object[z]=Object.create(null))
var x="_ZxYxX"
for(var w=0;;w++){var v=intern(x+"_"+w+"_")
if(!(v in y)){y[v]=1
init.isolateTag=v
break}}init.dispatchPropertyName=init.getIsolateTag("dispatch_record")}();(function(a){if(typeof document==="undefined"){a(null)
return}if(document.currentScript){a(document.currentScript)
return}var z=document.scripts
function onLoad(b){for(var x=0;x<z.length;++x)z[x].removeEventListener("load",onLoad,false)
a(b.target)}for(var y=0;y<z.length;++y)z[y].addEventListener("load",onLoad,false)})(function(a){init.currentScript=a
if(typeof dartMainRunner==="function")dartMainRunner(K.Q,[])
else K.Q([])})
})()
